= Introduction

== How to Read This Document

This is the Function Specification for the set of IKEv2 protocol module. IKEv2 protocol module is developed for the TTCN-3 Toolset with TITAN.

== Scope

The purpose of this document is to specify the content of the IKEv2 protocol module. Basic knowledge of TTCN-3 <<4-references.adoc#_2, [2]>> and TITAN TTCN-3 Test Executor <<4-references.adoc#_4, [4]>> is valuable when reading this document.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor version R8A (1.8.pl0) or higher installed.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R8A.

== Installation

The set of protocol modules can be used in developing TTCN-3 test suites using any text editor. However to make the work more efficient a TTCN-3-enabled text editor is recommended (e.g. `nedit`, `xemacs`). Since the IKEv2 protocol is used as a part of a TTCN-3 test suite, this requires TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<4-references.adoc#_3, [3]>>.

== Configuration

None.
