= Terminology

*Sockets:* +
The sockets is a method for communication between a client program and a server program in a network. A socket is defined as "the endpoint in a connection". Sockets are created and used with a set of programming requests or "function calls" sometimes called the sockets application programming interface (API). The most common socket API is the Berkeley UNIX C language interface for sockets. Sockets can also be used for communication between processes within the same computer.

*OpenSSL:* +
The OpenSSL Project is a collaborative effort to develop a robust, commercial-grade, full-featured, and open source toolkit implementing the Secure Socket Layer (SSL v2/v3) and Transport Layer Security (TLS v1) protocols as well as a full-strength general purpose cryptography library. For more information on the OpenSSL project see <<9-references.adoc#_5, [5]>>

== Abbreviations

IP:: Internet Protocol

IUT:: Implementation Under Test

LDAP:: Lightweight Directory Access Protocol

LDIF:: LDAP Data Interchange Format

RTE:: RunTime Environment

TCP:: Transmission Control Protocol

TTCN-3:: Testing and Test Control Notation version 3

SSL:: Secure Socket Layer
