= DsRestAPI

== Overview

The DsRestAPI feature is developed to provide APIs for the CLL Data Source. It also provides a sub-feature that collects timelines of data elements.

For more information about the Data Source and its purpose, please see <<8-references.adoc#_8, [8]>> and <<8-references.adoc#_9, [9]>>.

[[description_of_files_in_this_feature]]
== Description of Files in This Feature

The CLL DsRestAPI feature includes the following files:

* __EPTF_CLL_DsRestAPI_Definitions.ttcn__ - this TTCN-3 module contains common type definitions used by the DsRestAPI Component.
* __EPTF_CLL_DsRestAPI_Functions.ttcn__ - this TTCN-3 module contains the implementation of DsRestAPI functions.
* __EPTF_CLL_DsRestAPI_ExternalFunctions.cc__ - this module contains external functions for DsRestAPI.
* __EPTF_CLL_DsRestAPI_DSServer_Definitions.ttcn__ - this module contains the definitions for the TTCN API of the Data Source.
* __EPTF_CLL_DsRestAPI_DSServer_Functions.ttcn__ - this module contains the implementation of the TTCN API function.
* __EPTF_CLL_DsRestAPI_Timeline_Definitions.ttcn__ - this module contains the definitions for the Timeline sub-feature.
* __EPTF_CLL_DsRestAPI_Timeline_Functions.ttcn__ - this module contains the implementation of the Timeline sub-feature.
* __EPTF_CLL_DsRestAPI_Timeline_ExternalFunctions.cc__ - this module contains external functions for the Timeline sub-feature.
* __EPTF_CLL_DsRestAPI_Filter_Definitions.ttcn__ - this module contains the definitions for the filtering feature.
* __EPTF_CLL_DsRestAPI_Filter_Functions.ttcn__ - this module contains the implementation of the filtering functions.
* __EPTF_CLL_DsRestAPI_Storage_Definitions.ttcn__ - this module contains the definitions for the caching feature.
* __EPTF_CLL_DsRestAPI_Storage_Functions.ttcn__ - this module contains the implementation of the caching functions.
* __EPTF_CLL_DsRestAPI_HTTPServer_Definitions.ttcn__ - this module contains the common type definitions used by the DsRestAPI HTTPServer Component.
* __EPTF_CLL_DsRestAPI_HTTPServer_Functions.ttcn__ - this module contains the implementation of the DsRestAPI HTTP server.
* _DsRestAPIComm.js_ - the JavaScript module that contains the AJAX calls that can be used to communicate with the HTTP server.
* _DsRestAPI.js_ - the JavaScript module that contains the DsRestAPI API functions described in <<8-references.adoc#_5, [5]>>.
* _DsRestAPI.py_ - the Python module that contains the DsRestAPI API functions described in <<8-references.adoc#_5, [5]>>.

[[description_of_required_files_from_other_CLL_features]]
== Description of Required Files from Other CLL Features

The DsRestAPI feature depends on the following CLL features:

* `Base`
* `Common`
* `FreeBusyQueue`
* `DataSource`
* `HashMap`
* `Logging`
* `Variable`

== Description of Required External Features Outside CLL

* `TCCUsefulFunctions_CNL113472`
* `IPL4asp_CNL113531`

== Installation

Since `EPTF_CLL_DsRestAPI` is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of these functions. For more details on the installation of TTCN-3 Test Executor, see the relevant section of <<8-references.adoc#_2, [2]>>.

If not noted otherwise in the respective sections, the following are needed to use `EPTF_CLL_DsRestAPI`:

* Copy the files which belong to the CLL features listed in section <<description_of_files_in_this_feature, Description of Files in This Feature>> and <<description_of_required_files_from_other_CLL_features, Description of Required Files from Other CLL Features>> to the directory of the test suite or create symbolic links to them.
* Import the DsRestAPI test or write your own application using EPTF DsRestAPI.
* Create _Makefile_ or modify the existing one. For more details, see the relevant section of <<8-references.adoc#_2, [2]>>.
* Edit the config file according to your needs, see section <<configuration, Configuration>>.

[[configuration]]
== Configuration

The executable test program behavior is determined through the run-time configuration file. This is a simple text file which contains various sections. The usual suffix of configuration files is _.cfg_. For further information on the configuration file, see <<8-references.adoc#_2, [2]>>.

The DsRestAPI feature does not define any module parameters.

== General Usage

DsRestAPI provides three main ways to communicate with the Data Source. These three ways are: the TTCN API, the JavaScript API and the Python API.

DsRestAPI provides all three methods of communication, while the standalone DSServer only provides the TTCN API.

To use the DsRestAPI feature, perform the following steps:

1.  Extend your component with the `EPTF_DsRestAPI_CT` component
2.  Call the init function (`f_EPTF_DsRestAPI_init_CT`) of the DsRestAPI to initialize the feature
3.  Call the `f_EPTF_DsRestAPI_start` function to start the DSServer and HTTP server
4.  (Optional) Call `f_EPTF_DsRestAPI_Timeline_start` to start collecting timelines. For more information, see <<8-references.adoc#_5, [5]>>.
5.  We can now use the three APIs to issue requests:
a.  In TTCN environment use the `f_EPTF_DsRestAPI_DSHandler_processJSONRequest` function to process a request
b.  Use the functions of the JavaScript API to send HTTP requests to the HTTP server
c.  Use the Python API to send HTTP requests to the HTTP server
6.  Call `f_EPTF_Base_cleanup_CT` function before your component terminates

To use the standalone DSServer without starting the HTTP server, fewer steps are required:

1.  Extend your component with the `EPTF_DsRestAPI_DSServer_CT` component
2.  Call the init function (`f_EPTF_DsRestAPI_DSServer_init_CT`) of the DSServer to initialize the feature
3.  Use the `f_EPTF_DsRestAPI_DSHandler_processJSONRequest` function to process a request
4.  Call `f_EPTF_Base_cleanup_CT` function before your component terminates

To use the Timeline as a standalone feature, do the following:

1.  Extend your component with the `EPTF_DsRestAPI_Timeline_CT` component
2.  Call the init function (`f_EPTF_DsRestAPI_Timeline_init_CT`) of the Timeline to initialize the feature
3.  Use the data elements of the DsRestAPI Timeline DataSource Client to collect and access timelines.
4.  Call `f_EPTF_Base_cleanup_CT` function before your component terminates

See <<8-references.adoc#_5, [5]>> for more details about the API functions.
