= Functionality

The JSON v07 2006 protocol module implements the message structures of the related protocol <<5-references.adoc#_4, [4]>> in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

The JSON v07 2006 protocol module uses Titan’s TEXT encoding attributes <<5-references.adoc#_3, [3]>> and hence is usable with the Titan test toolset only.

== Implemented Protocols

This set of protocol modules implements protocol messages and constants of the JSON protocol as described in <<5-references.adoc#_4, [4]>>.

=== Modified and Non-Implemented Protocol Elements

Numbers: +
Numbers can only be integers with the digits specified. ".", "e+", "e-", "E+", "E-" are not handled. Fractions and exponentials are discarded when decoding.

=== Ericsson-Specific Changes

None.

== Backward Incompatibilities

None.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

Titan TTCN-3 Test Executor version CRL 113 200 R7A (1.7.pl0) or higher installed. For Installation Guide see <<5-references.adoc#_2, [2]>>.

NOTE: This version of the test port is not compatible with Titan releases earlier than CRL 113 200 R7A.
