= Terminology

*EPTF Core Library (CLL):* +
It is that part of the TitanSim software that is totally project independent. (i.e., which is not protocol-, or application-dependent). The Core Library is to be supplied and supported by the TCC organization. Any Core Library development is to be funded centrally by Ericsson.

*Application Library (Applib):* +
It is that part of the TitanSim software that is although protocol, or application-area dependent, but can be _reused_ across many TitanSim applications. Applibs are dependent on the CLL.

*Control Logic:* +
It is that part of the TitanSim software that is specific to a particular TitanSim application program. It is usually not directly reusable and is built upon the CLL and several Applibs.

*Entities:* +
They are "things/objects" that are simulated by the LGen. Such "things" are usually the "users", "calls", "servers", "terminations", or anything whose external behavior is to be simulated by the LGen. Usually an LGen simulates more than one entity.

*Entity context:* +
It is an indexable generic data record describing an entity. It stores index cross-references to _behavior contexts_ and it directly stores the _FSM contexts_ of the entity. The entity contexts are identified via their indices with respect to the entity context database stored in the `v_LGenBase_entities` component variable.

*Behavior context:* +
It is an indexable (set of) data record(s) that stores data and state information of a given entity with respect to a given _behavior type._ Storage for behavior contexts is to be provided by the respective Applibs.

*Behavior type:* +
It is a concept for collectively referring a set of _behavior contexts, FSM inputs, test steps,_ and functions realizing methods conforming to given function signatures prescribed by the LGenBase feature. Behavior types are to be declared dynamically during run-time to the LGenBase by the component-type initialization function of some Applib. Usually an Applib product has only one behavior type, but it is permitted for Applibs to declare more than one behavior types, if necessary. Behavior types are identified by their indices determined by the order of declaration and the declarations are stored in `v_LGenBase_behaviorTypes`

*Entity type:* +
It is a named list of references to declared _behavior types_. As such, it declares what type of behavior contexts are available on entities of this type.

*Entity group:* +
A group of entities with the same entity type. The indices of the entities of the group make a continuous interval that does not overlap with the index range of any other entity group.

*Test step:* +
Test steps are functions whose signature conforms to a given function type. They _must_ not contain TTCN-3 statements with blocking semantics.

*Event listener:* +
It is a call-back function to be dynamically registered that will be called whenever an _event reporter_ calls `f_EPTF_LGenBase_dispatchEvent`

*Reportable event:* +
It is a declared notification message of a given _behavior type_ that can be distributed to _event listeners_ by _event reporters_ via `f_EPTF_LGenBase_dispatchEvent`

*Event reporter:* +
It is an altstep, or function of a given _behavior type_ that eventually calls `f_EPTF_LGenBase_dispatchEvent`

*Reported event:* +
It is an instance of a _reportable event_ supplied with reported arguments that is actually being distributed via `f_EPTF_LGenBase_dispatchEvent`.

*Finite State Machine:* +
It is a formal description of _Control Logic_. It is a tabular description of what _test steps_ to call when a given _reported event_ occurs, when the entity is in a given declared _state of the FSM_. After executing these _test steps_ an optional next _FSM state_ can be also defined.

*FSM table:* +
It is a formal specification of the communication rules of Finite State Machines. These indexable records are stored in `v_LGenBase_fsmTables`. FSM tables realizing _traffic cases_ must obey certain rules.

*FSM state:* +
It is a locally indexed declaration of a state within an FSM table.

*FSM timer:* +
It is a locally indexed declaration of a timer within an FSM table.

*Traffic case type:* +
It is a prototype used as an input for instantiating traffic case instances on a specific entity group. It defines which _FSM table_ to use, which _entity type_ must be used by the _entity group_ where the _traffic case_ is to be deployed

*Traffic case:* +
It is a behavior, defined by an FSM table, that is executed on a given entity group. All entities of the entity group participate in executing the traffic case. An entity group may have more than one concurrent traffic cases.

*Group finish condition:* +
It is list of conditions that defines situations when a traffic case is over on group level, that is, no new traffic is launched on that group. Group finish conditions are evaluated whenever any entity of the group reports the event that it has just finished executing a traffic instance of that traffic case.

*Group finish actions:* +
It is list of action that is executed when any of the group finish conditions has been met.

*User finish condition:* +
It is list of conditions that defines situations when a _traffic case_ is over for a given entity, that is, the entity is not considered for selection for launching a new traffic, even if the entity returns to its idle _state_. User finish conditions are evaluated whenever any entity of the group reports finishing the traffic case, that is, returning to the "idle" state of the respective FSM context.

*User finish actions:* +
It is list of action that is executed when any of the _user finish_ conditions has been met.

*Scenario* +
It is a collection of traffic cases deployed on an entity group.

*Named functions:* +
They are functions that has an associated name (label), are declared to LGenBase metadata with that label; and can be invoked via their labels.

*External templates:* +
They are parameterized text modules are stored by LGenBase. Parameter values can be substituted dynamically during run-time.

*Template type:* +
It is a named declaration of a template assigned to a behavior type.

*Template set:* +
It is set of templates belonging to a traffic case. It is a list of `<template type, external template>` pairs.

= Abbreviations

CLL:: Core Library

EPTF:: Ericsson Performance Test Framework

TitanSim:: Ericsson Performance Test Framework

TTCN-3:: Testing and Test Control Notation version 3 See <<7-references.adoc#_1, [1]>>.
