= Test Port Usage

== Module Structure

The LANL2 test port is implemented in the following TTCN-3 blocks:

* __LANL2asp_Types.ttcn__
* __LANL2asp_PortType.ttcn__

The file __LANL2asp_Types.ttcn__ defines the `PDU_LANL2` and `ASP_LANL2`. The port type is defined in __LANL2asp_PortType.ttcn__.

The C++ implementation of the test port is contained in the following files:

* __LANL2asp_PT.cc__
* __LANL2asp_PT.hh__

== Installation

Since the LANL2 test port is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of the LANL2 test port. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<7-references.adoc#_2, [2]>>.

When building the executable test suite, the libraries compiled for the TTCN-3 Test Executor and the Libpcap library should also be linked into the executable. The Libpcap library shall be added to the _Makefile_ generated by the TITAN executor. See <<5-warning_messages.adoc#makefile, Makefile>> section of this document.

== Configuration

The executable test program behavior is determined via the run-time configuration file. This is a simple text file, which contains various sections (for example, `[TESTPORT_PARAMETERS]`) after each other. The usual suffix of configuration files is _.cfg_. For further information on the configuration file see Chapter 7 of <<7-references.adoc#_3, [3]>>.

=== LANL2 Test Port Parameters in the Test Port Configuration File

In the `[TESTPORT_PARAMETERS]` section the following parameters can be set for the LANL2 test port. The parameter names are case-sensitive.

`eth_interface_name`

This parameter is mandatory. The parameter can be used to specify the name of the interface used for sending and receiving messages.

`eth_mac_source`

This parameter is optional when sending `LANL2_PDU` and not used when sending `LANL2_ASP`. The parameter can be used to specify the source MAC address of the Ethernet II frame. If not set, the test port fills in the source MAC address from hardware (if possible).

`eth_mac_destination`

This parameter is mandatory when sending `LANL2_PDU` and not used when sending `LANL2_ASP`. The parameter can be used to specify the destination MAC address of the Ethernet II frame.

`eth_proto`

This parameter is mandatory when sending `LANL2_PDU` and not used when sending `LANL2_ASP`. The parameter can be used to specify which protocol is being transported in the Ethernet II frame.

`packet_filter`

This parameter is optional but should be set according to the specific usage. The user can specify here a Libpcap filter expression. The receiving of the packets will be filtered according to the expression. The format is exactly the same as the filter used by tcpdump <<7-references.adoc#_5, [5]>>. If not set, every packet will be transmitted.

`promiscuous_mode`

This parameter is optional. If set to `_"1"_`, the interface given by `eth_interface_name` will be set to promiscuous mode. Otherwise not. In promiscuous mode, network card passes all traffic it receives rather than just packets addressed to it.

NOTE: Even if this parameter is not `_"1"_`, the interface could well be in promiscuous mode for some other reason.

`dump_erroneous_frame`

This parameter is optional. If set to `_"1"_`, when receiving an Ethernet packet smaller than 60 bytes (without CRC) but bigger than 14 bytes the event is logged as warning with the packet size given, and the packet dumped.

`port_mode`

This parameter is optional. It controls the single or multi interface support of the test port. Possible values and behaviors:

* `single_interface` – The test port supports only one network interface. The interface is opened during the map operation. Usable messages: `ASP_LANL2`, `PDU_LANL2`, `ASP_LANL2_Error` (default)

* `multiple_interface` – The test port supports several network interfaces. Usable messages: `ASP_v2_LANL2`, `ASP_LANL2_open_interface`, `ASP_LANL2_close_interface`, `ASP_LANL2_open_result`, `ASP_v2_LANL2_Error`

`error_mode`

This parameter is optional. It controls the behavior of the test port in the case of the error during send operation. Possible values and behaviors:

* error – The test port issues a TTCN error if the send failed. (default)

* warning – The test port logs a warning message if the send failed.

* ignore – The test port silently ignores the sending errors.

* report – The test port sends an error ASP to the test case.
