= Introduction

== About This Document

=== How to Read This Document

This is the User Guide for the ICMPv6 protocol module. The ICMPv6 protocol module is developed for the TTCN-3 Toolset with TITAN. This document should be read together with Function Specification <<4-references.adoc#_4, [4]>>.

=== Presumed Knowledge

To use this protocol module the knowledge of the TTCN-3 language <<4-references.adoc#_1, [1]>> is essential.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor 1.8.pl0.pre2 or higher installed. Forinstallation guide see <<4-references.adoc#_3, [3]>>. 

NOTE: This version of the protocol module can not be used for defining 32bit unsigned or larger integers with TITAN versions earlier than 1.8.pl0.pre2. +
This version of the protocol module is not compatible with TITANreleases earlier than R7A.
