= References

[[_1]]
[1] ETSI ES 201 873-1 v3.1.1 (06/2005) +
The Testing and Test Control Notation version 3. Part 1: Core Language

[[_2]]
[2] Installation Guide for TITAN TTCN-3 Test Executor

[[_3]]
[3] User Guide for TITAN TTCN-3 Test Executor

[[_4]]
[4] https://www.ietf.org/rfc/rfc2045.txt[RFC 2045] +
Multipurpose Internet Mail Extensions (MIME) Part One: Format of Internet Message Bodies

[[_5]]
[5] https://www.ietf.org/rfc/rfc2849.txt[RFC 2849] +
The LDAP Data Interchange Format (LDIF) – Technical Specification

[[_6]]
[6] NaturalDocs document for TCC UsefulFunctions +
(/vobs/ttcn/TCC_Common/Libraries/TCCUsefulFunctions_CNL113472/doc/apidoc)

[[_7]]
[7] An example algorithm set for the 3GPP authentication and key generation functions f1, f1__, f2, f3, f4, f5 and f5__; Document 2: Algorithm Specification3GPP TS 35.206 (v7.0.0 2007-06)

[[_8]]
[8] 3GPP TS 33.102 V9.1.0 (2009-12) +
3rd Generation Partnership Project; Technical Specification GroupServices and System Aspects; 3G Security; Security architecture (Release 9)

[[_9]]
[9] 3GPP TS 34.108 V4.7.0 +
Common test environments for User Equipment (UE) conformance testing (Release 4) 2003.06.

[[_10]]
[10] Specification of the 3GPP Confidentiality and Integrity Algorithms128-EEA3 & 128-EIA3. Document 1: 128-EEA3 and 128-EIA3Specification, Version 1.6, 1st July, 2011

[[_11]]
[11] Specification of the 3GPP Confidentiality and Integrity Algorithms128-EEA3 & 128-EIA3. Document 2: ZUC SpecificationVersion 1.6, 28th June 2011

[[_12]]
[12] GSM 03.38 V7.2.0 +
Digital cellular telecommunications system (Phase 2+)Alphabets and language-specific information

[[_13]]
[13] ETR 060 +
Guidelines for using Abstract Syntax Notation One (ASN.1) in telecommunication application protocols

[[_14]]
[14] ITU-T Q.763 (12/1999) +
SERIES Q: SWITCHING AND SIGNALING +
Specifications of Signaling System No. 7 – ISDN user part Signaling System No. 7 – ISDN user part formats and codes

[[_15]]
[15] 3GPP TS 24.008 V12.0.0 (2012-12) +
3rd Generation Partnership Project; +
Technical Specification Group Core Network and Terminals; +
Mobile radio interface Layer 3 specification; +
Core network protocols; Stage 3(Release 12)

[[_16]]
[16] 3GPP TS 33.401 V12.14.0 (2015-03) +
3rd Generation Partnership Project; +
Technical Specification Group Services and System Aspects; +
3GPP System Architecture Evolution (SAE); +
Security architecture(Release 12)
