= Introduction

== About This Document

=== How to Read This Document

This is the User’s Guide for the SQL test port. The SQL test port is developed for the TTCN-3 Toolset with TITAN. This document is intended to be read together with Function Specification <<7-references.adoc#_3, [3]>>.

=== Prerequisite Knowledge

The knowledge of the TITAN TTCN-3 Test Executor <<7-references.adoc#_2, [2]>> and the TTCN-3 language <<7-references.adoc#_1, [1]>> is essential. Basic knowledge of the SQL is valuable when reading this document.

== System Requirements

In order to operate the SQL test port the following system requirements must be satisfied:

* Platform: any platform supported by TITAN RTE and the used SQL engine
* TITAN TTCN-3 Test Executor version R8A (1.8.pl0) or higher installed. For installation guide see <<7-references.adoc#_2, [2]>>. 

NOTE: This version of the test port is not compatible with TITAN releases earlier than R8A.

* The run time and the development libraries of the used SQL engine.
* SQLite engine required sqlite3 development library version 3.6.5 or later.

== Fundamental Concepts

The SQL test port executes SQL statement against the SQL database. The SQL test port is able to handle different SQL engines and databases, and provides a unified interface towards them.
