= Error Messages

The following Error messages are generated by the test port. Description is also included if the message is not self-evident.

== SQLite Interface

*ERROR:*

`*You have to specify positive max_busy_retries parameter.*`

`*Max retry reached. Giving up.*`

`*Database attribute is not specified. eg: file:/home/path/mydb.db*`

The mandatory "database" configuration file parameter is missing.

`*The SQLite engine is not connected to the database. Please connect first.*`

An SQL query is attempted without first sending an `SQL_Connect`.

`*Unknown field type*`

The field (column) received by the test port is not recognized.

`*Error with query.*``

Query has been attempted but resulted in error.

`*The database connection is associated with unfinalized prepared statements or unfinished sqlite3_backup objects.*``

Termination of the connection to the database is not successful.

`*Step is <result type> not SQLITE_ROW!*`

Only SQLITE_ROW result type can be returned after SQL SELECT.

`*Error while query: <result type>*`

Could not start query.

== MySQL Interface

`*ERROR: Can not initialize the MySQL library. The mysql_init returned NULL.*`

Unsuccessful initialization of MySQL connection based on the given parameters.

`*MySQL connect failed with error message: <error_message>.*``

Unsuccessful connection to MySQL. The error message is returned by MySQL. See <<7-references.adoc#_4, [4]>> for details.

`*The MySQL engine isn't connected to the database. Please connect first.*``

A MySQL query is attempted without first sending an `SQL_Connect`.

`*The SQL query failed with error message: <error_message>.`*

Unsuccessful query.The error message is returned by MySQL. See <<7-references.adoc#_4, [4]>> for details.

`*The mysql_store_result failed with error message: <error_message>.*`

The error message is returned by MySQL. See <<7-references.adoc#_4, [4]>> for details.

MySQL can return with other error messages. They can come directly from the MySQL server, so for more details see <<7-references.adoc#_4, [4]>>.
