= The Test Port

== Overview

The SunRPC test port offers Sun RPC message primitives and TCP connection control ASPs to the test suite in TTCN-3 format. The TTCN-3 definition of the Sun RPC messages and TCP connection ASPs can be found in a separate TTCN-3 module. This module should be imported into the test suite.

== Installation

Since the SunRPC test port is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of the SunRPC test port. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<7-references.adoc#_2, [2]>>.

When building the executable test suite intended to handle Sun RPC over SSL connections, the libraries compiled for the OpenSSL toolkit and the TTCN-3 Test Executor should also be linked into the executable.

Using and compiling OpenSSL is optional in the test port. See <<7-references.adoc#_5, [5]>> for more information. OpenSSL libraries should be added to the _Makefile_ generated by the TITAN executor see example in <<5-examples.adoc#makefile, Makefile>>.

== Configuration

The executable test program behavior is customized via the RTE configuration file. This is a simple text file, which contains various sections (e.g. `[TESTPORT_PARAMETERS]`) after each other. The usual suffix of the RTE configuration file is _.cfg._ For further information about the configuration file see <<7-references.adoc#_2, [2]>>.

[[SunRPC_Test_Port_Parameters_in_the_RTE_Configuration_File]]
=== SunRPC Test Port Parameters in the RTE Configuration File

In the `[TESTPORT_PARAMETERS]` section you can specify parameters that are passed to the test ports. Each parameter definition consists of a component name, a port name, a parameter name and a parameter value. The component name can be either an identifier or a component reference (integer) value. The port and parameter names are identifiers while the parameter value always must be a charstring (with quotation marks). Instead of component name or port name (or both of them) the asterisk ("*") sign can be used, which means "all components" or "all ports of the component". More information about the RTE configuration file can be found in <<7-references.adoc#_2, [2]>>.

In the `[TESTPORT_PARAMETERS]` section the following parameters can be set for the SunRPC test port. Parameters marked with bold fonts apply to *SSL* using SunRPC test ports *only*. Parameter values are *case-sensitive*!

`socket_debugging`

Enables detailed debugging in the test port. It has only effect when `TTCN_DEBUG` is also set within the logging parameters of the configuration file.

Its default value is `_"no"_`.

`*ssl_use_ssl*`

The parameter is optional, and can be used to specify whether to use SSL on the top of the TCP connection or not.

The default value is `_"no"_`.

`*ssl_use_session_resumption*`

The parameter is optional, and can be used to specify whether to use/support SSL session resumptions or not.

The default value is `_"yes"_`.

`*ssl_private_key_file*`

The parameter is *conditional*, and have to be passed to SSL enabled SunRPC server test ports. The KEYFILE specifies a 'pem' encoded file’s path on the file system containing the server’s RSA private key.

`*ssl_trustedCAlist_file*`

It specifies a PEM encoded file’s path on the file system containing the certificates of the trusted CA authorities to use. *Mandatory* for server, and *mandatory* for client *if* `ssl_verify_certificate`=`_"yes"_`.

`*ssl_certificate_chain_file*`

It specifies a PEM encoded file’s path on the file system containing the certificate chain. *Mandatory* for server and *optional* for client. Note that the server may require client authentication. In this case no connection can be established without a client certificate. For detailed information see <<7-references.adoc#_5, [5]>>.

`*ssl_private_key_password*`

The parameter is *optional*, and may be passed to SSL enabled SunRPC server test ports. The PASSWORD has to be the password used by generation of the server’s private key file. If the password is not defined, the SSL toolkit asks for it when the test port receives the `ASP_SunRPC_Listen` ASP. It is recommended to define it in the config file instead.

`*ssl_allowed_ciphers_list*`

The parameter is *optional*, and can be used to specify the allowed cipher list. The value is passed directly to the SSL toolkit.

`*ssl_verify_certificate*`

The parameter is *optional*, and can be used to tell the client SunRPC test port to check the server authentication. If it is defined `_"yes"_`, the test port will query and check the server’s certificate. If the certification is not valid, it will exit with a corresponding error message.

Its default value is `_"no"_`.

== Start Procedure

=== TTCN-3 Test Executor

Before the executable test suite can be run the TTCN-3 modules and C++ codes should be compiled and linked into an executable program. This process can be automated using the make utility. For more information about the _Makefile_ see section <<5-examples.adoc#makefile, Makefile>> and <<7-references.adoc#_2, [2]>>.

NOTE: The c++ implementation files __SunRPCasp_PT.hh__, __SunRPCasp_PT.cc__, __Abstract_Socket.hh.cc__, __Abstract_Socket.hh.hh__ (from product `Abstract_Socket' CNL 113 384) and the TTCN-3 modules SunRPCasp_Types.ttcn, and __SunRPCasp_PortType.ttcn__ should be included in the _Makefile_.

For information on how to start the execution see <<7-references.adoc#_2, [2]>>.

=== Connecting to a Server

In case of the test performs the role of a SunRPC client, the `ASP_SunRPC_Connect` ASP has to be sent. Its parameters are:

* `hostname` - host name or IP address of the remote server.

* `portnumber` - port number of the remote server where it accepts connections.

* `local_hostname` - select local interface for the local end of connection. It should be set if the workstation has multiple IP interfaces, and the test has to use a specific one.

* `local_portnumber` - select local port number for the local end of connection

Multiple parallel connections can be opened and used. `ASP_SunRPC_Connect_result` ASP is returned to the test case with the `client_id` associated to the opened connection. The returned `client_id` has to be used in the messages targeted to send on this connection. The returned `client_id` with value `_'–1'_` means that the server did not accept the connection because an error occurred.

=== Starting a Server, Listening for Client Connections

In case of the test performs the role of a SunRPC server, the `ASP_SunRPC_Listen` ASP has to be sent. Its parameters are:

* portnumber - port number where the server will accept connections.

* local_hostname - host name or IP address of the interface in the local computer. It should be set if the workstation has multiple IP interfaces, and the test has to use a specific one.

Sending the `ASP_SunRPC_Listen` ASP multiple times will cause the listening port to close and open another one.

The `ASP_SunRPC_Listen_result` ASP is returned to the test case with the opened port number. The returned `portnumber` with value `_'–1'_` means that an error occurred while setting up the requested listening port.

If a client connects to the server, the `ASP_SunRPC_Client_connected` ASP is sent to the test case with `hostname`, `portnumber` and `client_id` fields. `client_id` has to be used as described link:#373901801590994-client_id_usage[above].

[[sending-receiving-sunrpc-messages]]
== Sending/Receiving SunRPC Messages

The SunRPC test port is able to send and receive `SunRPC_message` and `SunRPC_message_multiple_client` structures. The `SunRPC_message_multiple_client` is a record of a `client_id` and a `SunRPC_message`, enabling the test suite to handle multiple clients through the same test port instance. The structure of the `SunRPC_message` message is described in <<7-references.adoc#_4, [4]>>.

The test port sends and receives the messages over the TCP/IP protocol, and does the encoding and decoding of the Record Marking Standard (see <<7-references.adoc#_4, [4]>>) automatically.

== Stop Procedure

[[asp-sunrpc-close]]
=== ASP_SunRPC_Close

The `ASP_SunRPC_Close` shuts down the client connection between the test port and the IUT. The `client_id` parameter of the `ASP_SunRPC_Close` ASP identifies the connection to be closed. If it is set to `_"omit"_`, all current connections will be closed.

The test suite receives `ASP_SunRPC_Close` if the remote end closes the connection.

[[asp-sunrpc-shutdown]]
=== ASP_SunRPC_Shutdown

Instructs the test port to close the server listening port. The client connections will remain open. The server will not accept further client connections until an `ASP_SunRPC_Listen` ASP is sent again.

[[ttcn-3-test-executor-0]]
=== TTCN-3 Test Executor

The TITAN executor stops the test port after the test case is finished or in case of execution error during the test case.
