= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of a draft DUA protocol (see <<5-references.adoc#_1, [1]>>). DUA is an extension to IUA; thus, part of the messages is defined in the draft IUA protocol <<5-references.adoc#_2, [2]>>.

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/deviations Related to the Protocol Specification

=== Implemented Messages

The following messages are defined in <<5-references.adoc#_1, [1]>>:

* Establish Request
* Establish Confirm
* Establish Indication
* Release Request
* Release Confirm
* Release Indication
* Data Request
* Data Indication
* DLC Status Request
* DLC Status Confirm
* DLC Status Indication

The following messages are defined in <<5-references.adoc#_2, [2]>>:

* ASP Up
* ASP Up Ack
* ASP Down
* ASP Down Ack
* ASP Active
* ASP Active Ack
* ASP Inactive
* ASP Inactive Ack
* Heartbeat
* Heartbeat Ack
* Error
* Notify

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

There is a conflict between the drafts <<5-references.adoc#_2, [2]>> and <<5-references.adoc#_1, [1]>>. For message class 0 (Management Messages) and message type 5 they define two different messages: DLC Status Request in <<5-references.adoc#_2, [2]>> and TEI Query Request in <<5-references.adoc#_1, [1]>>. To resolve this contradiction, message types for MGMT messages defined in chapter 2.4 of <<5-references.adoc#_2, [2]>> have been arbitrarily incremented by one. The new values are: `_6_` for DLC Status Request, `_7_` for DLC Status Confirm and `_8_` for DLC Status Indication.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions that assure correct encoding of messages when sent from Titan and correct decoding of messages when received by Titan. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`enc_PDU_DUA`
|PDU_DUA
|octetstring

|`DEC_PDU_DUA`
|octetstring
|PDU_DUA
|===

== Limitations

Debug log generation is not supported when this revision of this product is used with TITAN version R7A (1.7pl0), because the encoder/decoder functions, automatically generated by TITAN version R7A (1.7pl0) does not contain logging functions. Newer versions of TITAN supports the debug logging within the automatically generated encoder/decoder functions that can be activated by allowing the DEBUG_ENCDEC (see clause 7.2.3.2 of <<5-references.adoc#_4, [4]>> in TITAN runtime configuration files.
