= Buffer

== Overview

The EPTF Buffer component provides TTCN3 function access to the native buffer of Titan (<<5-references.adoc#_7, ‎[7]>>, chapter 3.1.2 - TTCN Buffer).

This component

* stores an octetstring and allows of querying, adding to, extending, completing it.
* supports the graceful termination feature of CLL Base in TitanSim ‎<<5-references.adoc#_8, [8]>>.

To be able to use EPTF Buffer, the user component should extend the `EPTF_Buffer_CT` component.

[[description_of_files_in_this_feature]]
== Description of Files in This Feature

The EPTF CLL Buffer API includes the following files:

* Buffer
** __EPTF_CLL_Buffer_Definitions.ttcn__ - This TTCN-3 module contains common type definitions used by the Buffer Component.
** __EPTF_CLL_Buffer_Functions.ttcn__ - This TTCN-3 module contains the implementation of Buffer functions.
** __EPTF_CLL_Buffer_ExternalFunctions.cc__ - This TTCN-3 module contains external functions for EPTF Buffer.

[[description_of_required_files_from_other_features]]
== Description of Required Files from Other Features

The EPTF Buffer feature depends on the following features of EPTF:

* `Base`

== Installation

Since `EPTF_CLL_Buffer` is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of these functions. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<5-references.adoc#_2, ‎[2]>>.

If not otherwise noted in the respective sections, the following are needed to use `EPTF_CLL_Buffer`:

* Copy the files listed in section <<description_of_files_in_this_feature, Description of Files in This Feature>> and <<description_of_required_files_from_other_features, Description of Required Files from Other Features>> to the directory of the test suite or create symbolic links to them.
* Import the Buffer test or write your own application using EPTF Buffer.
* Create _Makefile_ or modify the existing one. For more details see the relevant section of ‎<<5-references.adoc#_2, ‎[2]>>.
* Edit the config file according to your needs, see following section <<configuration, Configuration>>.

[[configuration]]
== Configuration

The executable test program behavior is determined via the run-time configuration file. This is a simple text file, which contains various sections. The usual suffix of configuration files is _.cfg_. For further information on the configuration file see ‎<<5-references.adoc#_2, [2]>>.

The EPTF Buffer feature does not define module parameters.
