= Terminology

*Sockets:* +
The socket is a method for communication between a client program and a server program in a network. A socket is defined as "the endpoint in a connection."" Sockets are created and used with a set of programming requests or "function calls" sometimes called the sockets application programming interface (API). The most common socket API is the Berkeley UNIX C language interface for sockets. Sockets can also be used for communication between processes within the same computer.

*Blocking and non-blocking sockets:* +
Using a blocking socket, some socket operations (send, receive, connect, accept) will block until the operation is finished or an error occurs. Using a non-blocking socket, these operations will never block but return with an error and set _errno_ to the appropriate value.

*OpenSSL:* +
The OpenSSL Project is a collaborative effort to develop a robust, commercial-grade, full-featured, and open source toolkit implementing the Secure Sockets Layer (SSL v2/v3) and Transport Layer Security (TLS v1) protocols as well as a full-strength general purpose cryptography library. For more information on the OpenSSL project see <<8-references.adoc#_3, [3]>>

= Abbreviations

AS:: Abstract Socket

ASP:: Abstract Service Primitive

IPv4:: Internet Protocol version 4

IPv6:: Internet Protocol version 6

PEM:: Privacy Enhanced Mail

RTE:: Run-Time Environment

SSL:: Secure Sockets Layer

SUT:: System Under Test

TCP:: Transmission Control Protocol

TLS:: Transport Layer Security

TTCN-3:: Testing and Test Control Notation version 3
