= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the DSS1 ETSI protocol, version 03/93 (see <<5-references.adoc#_1, [1]>>) with the modifications specified in <<modifications-deviations-related-to-the-protocol-specification, Modifications/Deviations Related to the Protocol Specification>>

In addition, the functional protocol specified in <<5-references.adoc#_5, [5]>> and in <<5-references.adoc#_6, [6]>> is implemented.

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Implemented Messages

The following messages are implemented from <<5-references.adoc#_1, [1]>>:

* `ALERTING`

* `CALL PROCEEDING`

* `CONGESTION CONTROL`

* `CONNECT`

* `CONNECT ACKNOWLEDGE`

* `DISCONNECT`

* `FACILITY`

* `HOLD`

* `HOLD ACKNOWLEDGE`

* `HOLD REJECT`

* `INFORMATION`

* `NOTIFY`

* `PROGRESS`

* `REGISTER`

* `RELEASE`

* `RELEASE COMPLETE`

* `RESTART`

* `RESTART ACKNOWLEDGE`

* `RESUME`

* `RESUME ACKNOWLEDGE`

* `RESUME REJECT`

* `RETRIEVE`

* `RETRIEVE ACKNOWLEDGE`

* `RETRIEVE REJECT`

* `SEGMENT`

* `SETUP`

* `SETUP ACKNOWLEDGE`

* `STATUS`

* `STATUS ENQUIRY`

* `SUSPEND`

* `SUSPEND ACKNOWLEDGE`

* `SUSPEND REJECT`

* `USER INFORMATION`

=== Functional Protocol

The implementation is based on files contained in annex "E" of <<5-references.adoc#_5, [5]>> and in <<5-references.adoc#_6, [6]>>

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

Protocol modules contain the following additions to <<5-references.adoc#_1, [1]>> (see <<5-references.adoc#_2, [2]>>):

* `NATIONAL REGISTER`

* `NATIONAL REGISTER ACKNOWLEDGE`

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions that assure correct encoding of messages when sent from TITAN and correct decoding of messages when received by TITAN. Implemented encoding/decoding functions. Via the backtrack decoder it is possible to avoid dynamic testcase error in case of trying to decode invalid message. In this case decoder function return a non-zero value:


[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`enc_PDU_DSS1`
|PDU_DSS1
|octetstring

|`dec_PDU_DSS1`
|octetstring
|PDU_DSS1

|`enc_PDU_DSS1_fast`
|PDU_DSS1
|octetstring

|`dec_PDU_DSS1_backtrack`
|octetstring, PDU_DSS1
|integer

|`enc_Facility_IE`
|Facility_IE
|octetstring

|`dec_Facility_IE`
|octetstring
|Facility_IE

|`enc_Facility_IE_fast`
|Facility_IE, octetstring

|`dec_Facility_IE_backtrack`
|octetstring, Facility_IE
|integer
|===

== Limitations

Debug log generation is not supported when this revision of this product is used with TITAN version R7A (1.7pl0), because the encoder/decoder functions, automatically generated by TITAN version R7A (1.7pl0) doesn't contain logging functions. Newer versions of TITAN supports the debug logging within the automatically generated encoder/decoder functions that can be activated by allowing the `DEBUG_ENCDEC` (see <<5-references.adoc#_4, [4]>> in TITAN runtime configuration files.
