= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the L2TP protocol. The modules are based on https://tools.ietf.org/html/rfc2661[RFC 2661] with the modifications specified in <<unimplemented_messages_information_elements_and_constants, Unimplemented Messages, Information Elements and Constants>> and <<protocol-modifications-deviations, Protocol Modifications/Deviations>>.

[[unimplemented_messages_information_elements_and_constants]]
=== Unimplemented Messages, Information Elements and Constants

None.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

None.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions, which assure correct RAW encoding of messages when sent from Titan and correct RAW decoding of messages when received by Titan. Implemented encoding/decoding functions:

[cols=3*, options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`enc_PDU_L2TP`
|PDU_L2TP
|octetstring

|`dec_PDU_L2TP`
|octetstring
|PDU_L2TP
|===

The hiding of AVP attribute values described in section 4.3 of <<5-references.adoc#_1, ‎[1]>> is implemented. The shared secret can be given as a configuration file parameter.
