= Examples

The "demo" directory of the deliverable contains the following examples:

* __EPTF_HostAdmin_demo.cfg__
* __EPTF_HostAdmin_demo.prj__
* __EPTF_HostAdmin_demo.ttcn__
* __makefile_patch.sh__

== _Makefile_

The _Makefile_ for projects using the Host Admin or Host Admin Base has to be modified from the _Makefile_ generated by TITAN.

The following modifications are needed in the _Makefile_ to be able to build the executable:

* Add "-lkstat –lpthread" to SOLARIS_LIBS and SOLARIS8_LIBS
* Add "-lpthread" to LINUX_LIBS and WIN32_LIBS

The example script __makefile_patch.sh__ in the demo directory can do this automatically.

== Configuration File

The used configuration file (__EPTF_HostAdmin_demo.cfg__) for the Host Admin example is placed in the demo directory.

Module parameters of the demo (additional to the ones described in <<2.5):

* `tsp_demoInterval`: interval of testing. Type: float, default: `_30.0_`.
* `tsp_demoRefreshPeriod`: refresh period for the local measurement test case in seconds. Type: float, default: 2.0.
* `tsp_demoHost`: host name or IP address for the remote measurement test case. Type: charstring, default: ``127.0.0.1''.
* `tsp_uiDemoHostList`: list of hosts for the `HostAdminUI` demo. If it is empty, `tsp_demoHost` is used instead.

== Demo Module

The demo module (__EPTF_HostAdmin_demo.ttcn__) illustrates a typical usage of the Host Admin feature.

There are three testcases in the demo:

* `tc_HostAdmin_RemoteMeasure`: example usage of the standalone Host Admin component.
* `tc_HostAdmin_LocalMeasure`: example usage of the Host Admin Base component.
* `tc_HostAdmin_GUI`: example usage of the `HostAdminUI`.
* `tc_HostAdminServer`: example usage of the Host Admin Server.
