= Introduction

== About This Document

=== How to Read This Document

This is the User Guide for the H.248 protocol module. The H.248 protocol module is developed for the TTCN-3 Toolset with TITAN. This document should be read together with Function Specification <<6-references.adoc#_5, [5]>>.

=== Presumed Knowledge

To use this protocol module the knowledge of the TTCN-3 language <<6-references.adoc#_1, [1]>> is essential.

Basic knowledge of the H.248 V2 and V3 protocol <<6-references.adoc#_6, [6]>>, <<6-references.adoc#_7, [7]>> and <<6-references.adoc#_9, [9]>> and SDP <<6-references.adoc#_8, [8]>> is valuable to use this protocol module.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor R8B (1.8.pl1) or higher installed. For installation guide see <<6-references.adoc#_4, [4]>>. Please note: This version of the protocol module is not compatible with TITAN releases earlier than R8B
