= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the SMTP protocol (see <<5-references.adoc#_1, [1]>>) and the ARPA Internet Text Messages (see <<5-references.adoc#_2, [2]>>) with the modifications specified in <<modifications-deviations-related-to-the-protocol-specification, Modifications/Deviations Related to the Protocol Specification>>.

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Implemented Messages

All of the SMTP commands, replies and message headers defined in <<5-references.adoc#_1, [1]>> are implemented.

Only the following message header fields implemented from <<5-references.adoc#_2, [2]>>:

* `Date`

* `From`

* `To`

* `Cc`

* `Bcc`

* `Sender`

* `Subject`

Any other header fields are treated as `Unknown_Header`.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

The type structure has been based on <<5-references.adoc#_2, [2]>> and <<5-references.adoc#_1, [1]>>, but the protocol module is able to handle the messages which are coded according to the newest version of the standards. See <<5-references.adoc#_5, [5]>> and <<5-references.adoc#_6, [6]>>.

[[encoding-decoding-functions]]
== Encoding/Decoding Functions

This product also contains encoding/decoding functions which assure correct encoding of messages when sent from Titan and correct decoding of messages when received by Titan. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name |Type of formal parameters |Type of return value
|`enc_SMTP_PDU` |(in SMTP_PDU pdu) |return charstring
|`dec_SMTP_PDU` |(in charstring stream) |return SMTP_PDU
|`enc_Mail_PDU` |(in Mail_PDU pdu) |return charstring
|`dec_Mail_PDU` |(in charstring stream) |return Mail_PDU
|`enc_Mail_PDU_utf8` |(in Mail_PDU_utf8 pdu) |return octetstring
|`dec_Mail_PDU_utf8` |(in octetstring stream) |return Mail_PDU_utf8
|===
