= `ILog`

== Overview

Logging every traffic case not only can result in unnecessarily huge log files, but it even makes logs less useable thus harder to find the cause of the failure. The EPTF CLL `ILog` feature makes it possible not to log successful traffic cases, only the failed ones.

[[descrip_files_this_feature]]
== Description of Files in This Feature

The EPTF CLL Improved Logging API includes the following files:

* ILogBase
** __EPTF_CLL_ILogBase_Definitions.ttcn__ - This TTCN-3 module contains common type definitions that should be used in all `ILog` components.
** __EPTF_CLL_ILogBase_Functions.ttcn__ - This TTCN-3 module contains the implementation of `ILog` functions.
* `ILogString`:
** __EPTF_CLL_ILogString_Definitions.ttcn__ - This TTCN-3 module contains the type definitions of the `ILogString` feature.
** __EPTF_CLL_ILogString_Functions.ttcn__ - This TTCN-3 module contains the function implementations of the `ILogString` feature.
* `ILog`:
** __EPTF_CLL_ILog_Definitions.ttcn__ - This TTCN-3 module contains the type definitions of the `ILog` feature.
** __EPTF_CLL_ILog_Functions.ttcn__ - This TTCN-3 module contains the function implementations of the `ILog` feature.


[[descr_req_files_other_feat]]
== Description of Required Files From Other Features

The `ILog` feature is part of the TitanSim EPTF Core Load Library (CLL). It relies on several features of the CLL. The user has to obtain the products/files to be found under the respective feature names:

* `Base`
* `Common`
* `FreeBusyQueue`
* `HashMap`
* `LGenBase`
* `NQueue`
* `TCCUsefulFunctions`

== Installation

Since EPTF CLL ILog is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of these functions. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<7-references.adoc#_2, [2]>>.

If not otherwise noted in the respective sections, the following are needed to use `EPTF_CLL_ILog`:

* Copy the files listed in section <<descrip_files_this_feature, Description of Files in This Feature>> and <<descr_req_files_other_feat, Description of Required Files From Other Features>> to the directory of the test suite or create symbolic links to them.
* Import the Improved Logging demo or write your own application using `ILog`.
* Create _Makefile_ or modify the existing one. For more details see the relevant section of <<7-references.adoc#_2, [2]>>.
* Edit the config file according to your needs. See the following section <<configuration, Configuration>>.

[[configuration]]
== Configuration

The executable test program behavior is determined via the run-time configuration file. This is a simple text file, which contains various sections. The usual suffix of configuration files is _.cfg_. For further information on the configuration file see <<7-references.adoc#_2, [2]>>.

The `ILog` feature defines TTCN-3 module parameters as defined in <<7-references.adoc#_2, [2]>>, clause 4. Actual values of these parameters – when there is no default value or a different from the default actual value to be used – shall be given in the `[MODULE_PARAMETERS]` section of the configuration file.

This feature does not contain any `ILog`–specific module parameters.
