= Functionality

The DIAMETER protocol module (for example, __DIAMETER_Types.ttcn__) is generated dynamically from the input DDF files using a shell script, which performs this with the help of an AWK script (<<2-general_overview.adoc#DPMG_Architecture, DPMG Architecture>>).

The naming of DDFs should follow the `<Official-Vendor-Id><Official-Application-Name>AVPs_<Application-Version>` scheme. The extension MUST NOT be _.ttcn_; _.ddf_ is recommended.

If the application uses only a minor sub-set of some standard specification then it is acceptable to define these AVPs in the framework of the new application instead of including all unnecessary AVPs of the standard.

The type definitions for testing protocols comply the Diameter Base Specification are split in two DDFs:

[width="100%",cols="40%,50%",options="header",]
|===========================================================================
|DDF name |Contents
|`BaseTypes_IETF_RFC3588` |Diameter Base Protocol <<9-references.adoc#_3, [3]>> related type definitions
|`Base_IETF_RFC3588` |Diameter Base Protocol <<9-references.adoc#_3, [3]>> AVP type definitions
|===========================================================================

The `AVP.awk` script merges its argument DDFs into a single valid TTCN-3 module called `DIAMETER_Types` by default.

The input DDFs must comply with the naming and typographical conventions described herein in order for the `AVP.sh` script to produce a syntactically and semantically valid TTCN-3 module.

== Naming Conventions

The generated identifiers of types are based on information provided in comments within the DDFs themselves.

1. Applications are distinguished using the unique `<Application-Name>` and `<Application-Revision>`, which are assigned by TCC. The `<Application-Name>` is used to prefix type as well as certain field identifiers in the generated TTCN-3 module to ensure unique naming. The `<Application-Revision>` is only optionally used in prefixes. The `<Application-Name>` and `<Application-Revision>` are hard-coded in each TTCN-3 FILE using the following format:
+
[source]
----
// APPLICATION-NAME: NASREQ

// APPLICATION-REVISION: Draft17
----

2. AVP properties (e.g. name, code, vendor-id) are enlisted in C++ style comment right before the AVP type definition using the following format:
+
[source]
----
// AVP: <Official-AVP-Name> (<Official-AVP-Code>) <Official-Vendor-Id> (<Official-Vendor-Id-Code>)

type Type_Specifier Official_AVP_Name …
----

3. The entire comment line with the information MUST stand in the same line (no line breaks when it splits to multiple lines).

4. The TTCN-3 type definition following a properly formed comment line is interpreted as an AVP definition, if the type identifier matches the `<Official-AVP-Code>` appearing in the comment before.

5. The `<Official-AVP-Name>`, `<Official-AVP-Code>`, `<Official-Vendor-Id>` and `<Official-Vendor-Id-Code>` shall come from the relevant RFC, IETF Draft or other specification.

6. The `<Official-Vendor-Id>` and `<Official-Vendor-Id-Code>` must be omitted if V bit is not set (i.e. `<Official-AVP-Name>` and `<Official-AVP-Code>` are unique)!

7. The TTCN-3 identifiers used in `<Official-AVP-Name>` and `<Official-Vendor-Id>` must keep the original naming except when this collides with TTCN-3 identifier’s naming rules:
+
[loweralpha]

a. Hyphens and spaces must be replaced by a single underscore

b. Trailing ``AVP'' SHOULD be omitted if not part of the name

8. The `<Official-AVP-Code>` and `<Official-Vendor-Id-Code>` must be given as integer numbers!

=== Key to Unique Naming of Identifiers

The following uniqueness criteria – derived from Diameter <<9-references.adoc#_3, [3]>> – must hold for identifiers used in DDFs:

1.  `<Application-Name>` or `<Application-Revision>` MAY NOT be globally unique.
2.  `<Application-Name>` AND `<Application-Revision>` MUST be globally unique: +
Each application identifier must be formulated so that it is always unique. It can happen that different drafts of the same application are used together that is why it is strongly recommended to prefix with `<Application-Revision>`, too!
+
Example 1
+
[source]
<Application-Name>s: BASE, NASREQ
+
Example 2
+
[source]
<Application-Revision>s: RFC3588, Draft17Combined prefixes: BASE_RFC3588, NASREQ_Draft17

3.  `<Official-AVP-Name>` may not be unique: +
It happens that the same AVP name is used in the same or in different Diameter applications. The script is designed to cope with this, thus it is recommended to keep the standard AVP name with respect to naming conventions.
+
Example
+
[source]
<Official-AVP-Name>s: Multi_Round_Time_Out

4.  `<Official-AVP-Code>` AND `<Official-Vendor-Id>` MUST be globally unique (except within different revisions of the same application!) since these two 32Bits numbers determine the AVP.
5.  `<Official-AVP-Name>` AND `<Official-Vendor-Id>` MUST be unique within an application
6.  `<Application-Name>` AND `<Official-AVP-Name>` AND `<Official-Vendor-Id>` MUST be globally unique

=== How to Model Enumeration Type AVPs in DDFs?

It is important to ensure the unique naming of enumeration type identifiers and enumeration items. Each enumerated type AVP requires a single type definition: The enumerated type definition containing the valid enumeration items. The identifier of the enumeration type shall be `<Official-AVP-Name>`.

The `AVP.sh` script generates Unsigned32 type AVP for each enumerated type AVP when the `enum_2_Unsigned32` option is turned on.

All enumerations in DDFs will get the following attributes automatically assigned to enumeration type AVPs' enumerations:

[source]
----
with \{
variant ``FIELDLENGTH(32)''
variant ``BYTEORDER(last)''
variant ``COMP(2scompl)''
}
----

`Command_Code` enumeration type can be extended in Diameter applications. DPMG merges them together into a single type definition with proper attributes. Duplicates are removed when some enumeration items appear multiple times within `Command_Code` definitions of the input DDF files.

== Script Operation

The TTCN-3 module, containing all relevant type definitions, is generated automatically from the relevant DDFs by a script. This ensures that no collision can appear between proper Diameter applications.

The top-level Diameter PDU to send/receive is always `PDU_DIAMETER`.

=== Load and Parse All Input Files

If overlapping AVP codes (same AVP code and Vendor-Id) are found during parsing of DDFs then the created TTCN-3 module (for example, `DIAMETER_Types`) will contain only the AVP found first. (This can happen when trying to use many different or identical revisions of the same Diameter application.)

=== Type Identifiers

The script changes AVP type identifiers in order to avoid name collisions. The `<Official-Application-Name>`(and optionally the `<Official-Application-Revision>`) and `<Official-Vendor-Id>` will prefix the `Official_AVP_Name` defined in DDF.

Example of AVP type definition in DDF:

[source]
----
// RFC 3588 8.14
// AVP: User-Name (1)
type AVP_UTF8String User_Name;
----

The corresponding type definition in the generated module (no Vendor-Id is allowed for User-Name AVP of Diameter Base specification `(<Application-Name>=BASE))`:

[source]
----
// AVP: User-Name (1)
type AVP_UTF8String BASE_NONE_User_Name;
----

If the `<Official-AVP-Name>` begins with `<Official-Vendor-Id>` then it is recommended to remove this from the `<Official-AVP-Name>` as the `<Official-Vendor-Id>` is always used to prefix AVP type definitions!

When the `<Vendor-Id>` of `<Official-AVP-Name>` is in category MUST NOT, then the `<Vendor-Id>` MUST NOT appear in the AVP comment line. `_"NONE"_` is used in the identifier of the generated AVP type definition when `<Official-Vendor-Id>` is absent.

[[vendor-id]]
=== `Vendor_Id`

Create `Vendor_Id` enumerated type containing all vendor ids that were found in the comment fields. The `Vendor_Id` type shall be used to determine the valid AVP code set (`AVP_Code_<Application-Name>_<Official-Vendor-Id>`) in the `AVP_Code` union.


[source]
----
type enumerated Vendor_Id \{
    // for each vendor id found in FILEs
    vendor_id_<Official-Vendor-Id> (<Official-Vendor-Id-Code>)
} with \{
  variant ``FIELDLENGTH(32)''
  variant ``BYTEORDER(last)''
  variant ``COMP(2scompl)''
}
----

The `Vendor_Id` codes are assigned by IANA according to ASSIGNNO [RFC3232], which is now obsoleted by an on-line database at http://www.iana.org/assignments/enterprise-numbers. The database contains over 23000 entries thus using a predefined `Vendor_Id` type is not appropriate!

NOTE: This `Vendor_Id` type will not clash with the Vendor-Id AVP of Diameter base specification as the AWK script alters the identifier of the latter type definition!

[[avp-code-official-vendor-id]]
=== `AVP_Code_<Official-Vendor-Id>`

Putting all AVP codes into a single enumerated type does not work because `<Official-AVP-Code>` is not globally unique. We can create unique identifiers for enumeration items but some enumeration items could have the same numeric value assigned, which is forbidden in TTCN-3. Separate `AVP_Code_<Official-Vendor-Id>` enumerations have to be created for each found Vendor-Id. The enumeration items themselves will be the AVP names prefixed with `avp_code_`, `<Application-Name>` and `<Official-Vendor-Id>`!

[source]
----
type enumerated AVP_Code_<Official-Vendor-Id> \{
    avp_code_<Application-Name>_<Official-AVP-Name>
                                                (<Official-AVP-Code>)
} with \{
    variant ``FIELDLENGTH(32)''
    variant ``BYTEORDER(last)''
    variant ``COMP(2scompl)''
}
----

For those AVPs where the `<Official-Vendor-Id>` MUST NOT be present, `_"NONE"_` shall be used as prefix!

[[avp-code]]
=== `AVP_Code`

The `AVP_Code` itself is a union type consisting of the `AVP_Code_<Official-Vendor-Id>` enumerations.

[source]
----
type union AVP_Code \{
    // for each vendor id found in DDFs
    AVP_Code_<Official-Vendor-Id> vendor_id_<Official-Vendor-Id>
}
----

[[avp-header]]
=== *__AVP_Header__*

The *__AVP_Header__* type must be generated because the RAW attributes must be inserted for correct decoding of `AVP_Code` union.

[source]
----
type record AVP_Header \{
    AVP_Code avp_code,
    BIT8 VMPxxxxx,
    UINT24 avp_length,
    Vendor_Id vendor_id optional
} with \{
    variant (vendor_id) “PRESENCE( \{
            VMPxxxxx = '10000000'B,
            VMPxxxxx = '10100000'B,
            VMPxxxxx = '11000000'B,
            VMPxxxxx = '11100000'B
} )"
variant (avp_code) “CROSSTAG(
            // for all AVP_Code union members
            vendor_id_<Official-Vendor-Id>,
                    vendor_id = vendor_id_<Official-Vendor-Id>;
    )"
}
----

For proper decoding it is important to set the spare bits to zero as required by the Diameter base specification <<9-references.adoc#_3, [3]>>.

[[avp-data]]
=== `AVP_Data`

The `AVP_Data` type is a generated union type containing all AVP types found in the DDFs:

[source]
----
type union AVP_Data \{
    <Application-Name>__<Official-Vendor-Id>__<Official-AVP-Name>
            avp_<Application-Name>__<Official-Vendor-Id>__<Official-AVP-Name>,
    octetstring avp_UNKNOWN
}
----

`avp_UNKNOWN` contains the erroneous AVP when something went wrong during the decoding of the AVP data.

=== AVP

The AVP type is a record that consists of two fields: the header `avp_header` and the data `avp_data`.

[source]
----
type record AVP \{
  AVP_Header avp_header,
  AVP_Data avp_data
} with \{
  variant ``PADDING(dword32)''
  variant (avp_header) ``LENGTHTO(avp_header, avp_data)''
  variant (avp_header) ``LENGTHINDEX(avp_length)''
  variant (avp_data) “CROSSTAG(
            // for all union fields
            avp_<Application-Name>__<Official-Vendor-Id>__<Official-AVP-Name>,
            avp_header.avp_code.vendor_id_<Official-Vendor-Id> =
            avp_code_<Application-Name>_<Official-AVP-Name>;
            // last entry
            avp_UNKNOWN, OTHERWISE
  )"
}
----

=== `GenericAVP`

The `GenericAVP` type is a union that was defined for error handling purposes.

[source]
----
type union GenericAVP \{
  AVP avp,
  octetstring avp_UNKNOWN
}
----

The `avp` field contains an AVP if it was correctly decoded, while the `avp_UNKNOWN` will contain the erroneous AVP with the header when something went wrong during the decoding.

[[command-code]]
=== `Command_Code`

`Command_Code` enumeration type is merged together from the DDF file of different application’s `Command_Code` definition by the AWK script. All enumeration item defined in different application are collected together and written to the generated __DIAMETER_Types.ttcn__ file. Proper encoding attributes are added to the `Command_Code` type by the script.

=== Output TTCN-3 Module

All definitions of DDF files, which are not subject to change are written to the output TTCN-3 module (for example, __DIAMETER_Types.ttcn__) file as is.

[[output-encoder-decoder]]
=== Output Encoder/Decoder

Optionally it is possible to generate a speed optimized __DIAMETER_EncDec.cc__ encoder/decoder instead of the RAW encoder and the default __DIAMETER_EncDec.cc__.

=== Detailed VMP and RPET Bits

The type definition of the RPET bits of the `Diameter` header and the VMP bits of the `AVP` header can be:

* 8 bit wide bitfield (BIT8) (traditional representation)

* Every bit is represented as a single bit (BIT1)

The handlings of these bits are controlled by the parameter of the generator script.

=== Bigint Support for Unsigned32 and 64 Bit Integer

The 32 bit unsigned integer and 64bit integer types can be represented as:

* 4 or 8 octet long octetstring

* integer

The used type is controlled by the parameter of the generator script.

== Backward Incompatibilities

[[cxdxinterface-ericsson-1551-fay301-0059-pc26-ddf]]
=== __CxDxInterface_Ericsson_1551_FAY301_0059_PC26.ddf__

Until version R24B The ddf file contained duplicated AVPs with __Ericsson_Specific_AVPs.ddf__. In version R24C, these duplications were removed and the prefix of the AVPs was chaged from `ECX_` to `E_`. This change is not backward compatible.

== System Requirements

The `DIAMETER` protocol module generator consist of several DDF files, contains different application definitions of Diameter protocols, a `GNU AWK` and shell script which reads the DDF files and generates the type definition module (__DIAMETER_Types.ttcn__ by default).

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor R7A (1.7.pl0) or higher installed. For installation guide see <<9-references.adoc#_2, [2]>>.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R7A.

== Installation

The set of protocol modules can be used for developing TTCN-3 test suites using any text editor. However, to make the work more efficient a TTCN-3-enabled text editor is recommended (for example, `nedit`, `xemacs`). Since the Diameter protocol is used as a part of a TTCN-3 test suite, this requires Titan TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<9-references.adoc#_2, [2]>>.

The `AVP.sh` shell script runs on Bourne Shell, which is usually available on a all UNIX like workstations. The `AVP.awk` script, which processes the DDF files and creates the DIAMETER protocol module, can be executed with `GNU AWK` version 3.1.6 or later <<9-references.adoc#_4, [4]>> so it must be available on the system.

[[generation-of-the-diameter-types-ttcn]]
== Generation of the ___5DIAMETER_Types.ttcn_5__

First you need to obtain the required DDF files. After you have the DDF files containing the definitions of the selected Diameter applications, you can generate the proper Diameter type definitions module by issuing for example the following command:

[source]
AVP.sh DiameterBaseAVPs.ddf DiameterBaseTypes.ddf OtherApplications.ddf

The above command generates the TTCN-3 type definition by merging the content of DDF files into module `DIAMETER_Types` into file __DIAMETER_Types.ttcn__. The script filters out duplicate AVP definitions by placing only the first one into the generated TTCN-3 module. Skipped definitions are annotated with warnings.

The script can be optionally invoked with some options. The options modify script operation. The options must appear in the argument list before the DDF files. Each option is introduced with the `–v` flag. The options must not immediately follow the `–v` flag; whitespace separation is required. The options themselves must be written in one word.

=== Supported Options

The supported options are:

* `module_id`: +
This option can be used to alter the identifier of generated TTCN-3 module. The `module_id` shall be a valid TTCN-3 identifier but must not contain underscore.

* `use_application_revision`: +
This option results the application revision string to be added as prefix to generated identifiers. The application revision string is hardcoded into the input DDF files. This option is disabled by default.

`use_bigint`: +
This option makes the script to use integer for UINT32, INT64 and UINT64 types instead of octetstring. This option is disabled by default.

`detailed_bits`: +
This option makes the script to generate detailed type definition for VMP and RPET bits. This option is disabled by default.

`disable_prefix`: +
This option makes the script to generate identifier names and a fixed `"AVP"` prefix instead of using the application name specified in the ddf file. This option is disabled by default.

`enum_2_Unsigned32_list=<list file name>`: +
This option makes the script to generate the listed AVP as Unsigned32 instead of enumerated type.

`custom_enc`: +
This option makes the script to generate c++ encoder/decoder function instead of using the RAW encoder. This function generates a complete new __DIAMETER_EncDec.cc__.

`use_UTF8_encoding`: +
This option defines AVP_UTF8String as universal charstring which will be encoded in UTF-8. This option can be used only together with `custom_enc`.

The next command stores the generated TTCN-3 definitions in module XYZ and translates all enumeration type AVPs to Unsigned32:

[source]
AVP.sh –v module_id=XYZ –v enum_2_Unsigned32=true DiameterBaseAVPs.ddf DiameterBaseTypes.ddf _OtherApplications.ddf_


NOTE: `AVP.sh` requires `AVP.awk` and – in case of specifying the `module_id` option – the __DIAMETER_EncDec.cc__ C++ source file for its operation!

The next command stores the generated TTCN-3 definitions in module XYZ, generates a __DIAMETER_EncDec.cc__ and `AVP_UTF8String` will be defined as universal charstring encoded as UTF-8.

[source]
----
AVP.sh –v module_id=XYZ –v custom_enc=DIAMETER_EncDec.cc -v use_UTF8_encoding=true DiameterBaseAVPs.ddf DiameterBaseTypes.ddf _OtherApplications.ddf_
----

=== ___Makefile___ Preparation

In case you want to add the task of generation of __DIAMETER_Types.ttcn__ module into your _Makefile_, you should do the following:

1. Generate the _GNU Makefile_ for your existing TTCN-3 and C++ files, except __DIAMETER_Types.ttcn__.

2. Add __DIAMETER_Types.ttcn__ manually to the list of the TTCN-3 sources into the generated _Makefile_.

3. Add the following rules to your _Makefile_:
+
[source]
----
DIAMETER_Types.ttcn: DiameterBaseTypes.ddf DiameterBaseAVPs.ddf <Input FILEs containing AVP definitions>

AVP.sh latexmath:[$(filter %.ddf,$]^)
----

When you use GUI for building executable, on top of normal project creation you should take care of the following:

1.  Add `AVP.awk` script and all DDF files you need to add to the `misc` files section.

NOTE: You must generate softlinks to the build directory with selecting the files and select 'Generate Softlinks' menu item manually as it is not generated automatically by the GUI.

2.  Create a script to modify the generated _Makefile_. List all the DDF files you need when executing the `AWK` script.
3.  Add script to modify the _Makefile_ in the project properties.
4.  If you want to have the _DIAMETER_Types.ttcn_ file added to your project, you can, but after adding, you should exclude the file from build in order to avoid double occurrence in the _Makefile_.

== Helper Functions

Two separate external functions are available for generating End-to-End and a Hop-by-Hop identifiers:

[source]
external function f_DIAMETER_genHopByHop() return octetstring;

This function generates a 4 octet long Hop-by-Hop identifier. The values returned are based on random number generation.

[source]
external function f_DIAMETER_genEndToEnd() return octetstring;

The function above generates a 4 octet long End-to-End identifier according to <<9-references.adoc#_5, [5]>>. The high order 12 bits contain the low order 12 bits of current time, and the low order 20 bits contain a random value.

It is important to mention, that if the Hop-by-Hop-Identifier or the End-to-End-Identifier is set to `_"0"_`, the encoder function automatically generates a value with the help of the presented two functions.

One external function is available to acquire an AVP by AVP code from an encoded Diameter PDU.

[source]
----
external function f_DIAMETER_GetAVPByListOfCodes(in octetstring pl_oct, in integerList pl_codeList) return octetstring;
----

The function accepts a list of AVP codes and will return the octetstring AVP value of the first AVP in the encoded Diameter PDU whose AVP code is in the list. Providing multiple AVP codes can be useful if the same AVP type can appear in the message with different AVP codes (for example, public id).

[source]
----
external function f_DIAMETER_GetAVPByListOfCodesCombined(in octetstring pl_oct, in integerList pl_codeList,in integerList pl_groupcodeList) return octetstring;
----

The purpose of this function is the same as the `f_DIAMETER_GetAVPByListOfCodes`, except `f_DIAMETER_GetAVPByListOfCodesCombined` searches also within the grouped AVPs listed in the `pl_groupcodeList` list.

[[encoding-decoding-functions]]
== Encoding/Decoding Functions

This product also contains encoding/decoding functions that assure correct encoding of messages when sent from Titan and correct decoding of messages when received by Titan. Implemented encoding/decoding functions:

[cols=3*, options=header]
|===

|Name
|Type of formal parameters
|Type of return

|`valuef_DIAMETER_Enc`
|(in PDU_DIAMETER pl_pdu)
|octetstring;

|`f_DIAMETER_Dec`
|(in octetstring pl_oct)
|PDU_DIAMETER;
|===

== Error Handling

During the decoding of a Diameter message the following error scenarios can be identified:

* If a Diameter message arrives with a command code not known by the Diameter protocol module, an error message is generated, where the unknown command code value appears at <value>:

[source]
----
Warning: While RAW-decoding type `@DIAMETER_Types.PDU_DIAMETER': Invalid enum value <value> for `@DIAMETER_Types.Command_Code'
----

* In case of an unknown AVP code, the AVP is decoded into a special `avp_UNKNOWN` field that contains the entire AVP with the header in its octetstring form. If the length of the AVP cannot be determined then the rest of the Diameter message is also put into this kind of AVP.
* If there is an AVP in the Diameter message, where the V bit is incorrectly set to `_"1"_`, but it doesn’t contain an optional Vendor-Id field, the decoder first tries to interpret the octets as a Vendor-Id and if it isn’t a known Vendor-Id value, then the decoder can detect it and sets this field to omit. The octets will be treated as data further on.
* In case there is an AVP in the Diameter message, where the V bit is incorrectly set to `_"0"_`, but it contains an optional Vendor-Id field, it is decoded into the special `avp_UNKNOWN` field.
* When an AVP appears with an unexpected Vendor-Id, it is decoded into the special `avp_UNKNOWN` field.

== Limitations

`<Application-Revision>` field in DDF files are not handled yet by the script. The reason is no application makes the `<Application-Revision>` info essential.
