= Introduction

== About This Document

=== How to Read This Document

This is the User Guide for the DSS1 protocol module. The DSS1 Layer 3 protocol module is developed for the TTCN-3 Toolset with TITAN. This document should be read together with Function Specification <<4-references.adoc#_3, [3]>>.

=== Presumed Knowledge

To use this protocol module the knowledge of the TTCN-3 language <<4-references.adoc#_1, [1]>> is essential.

DSS1 is specified in the Function Specification <<4-references.adoc#_4, [4]>> and the Recommendation <<4-references.adoc#_5, [5]>>. Functional protocol is described in <<4-references.adoc#_6, [6]>> and in <<4-references.adoc#_7, [7]>>.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor R7A (1.7.pl0) or higher installed. For installation guide see <<4-references.adoc#_2, [2]>>.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R7A.
