= Functional Specification

== Protocol Version Implemented

This application library implements basic protocol behavior of the HTTP protocol based on <<5-references.adoc#_1, [1]>> and <<5-references.adoc#_2, [2]>>. Modifications/deviations related to the protocol specification.

=== Implemented Functionality

The application library is able to send HTTP queries or responses, maintains a number of built-in statistics and handles different transport modes.

==== HTTP Context

The application library provides a HTTP context database which is used to store user related information. Common data for requests and responses:

* Major version number
* Minor version number
* header lines: a sequence of HTTP header name and value pairs
* connection id: the unique id of an HTTP connection object
* message body: HTTP message body (it can be binary body)

Data for requests:

* method: HTTP method (for example, POST, GET, etc.)
* URI: HTTP request URI
* authentication details: authentication details of the user

Data for responses:

* `statusCode`: status code of the response
* `statusText`: status text of the response

Above information is used to build an HTTP message.

==== HTTP Statistics

Counter statistics are provided for incoming and outgoing messages. The number of incoming and outgoing messages is counted based on HTTP method and HTTP status code properties.

==== HTTP Transport

A port group is a set of ports with a unique id. A port group contains one ore more ports. Ports are representing connections and listen sockets. The user can perform an operation on the port group using its unique id.

HTTP messages are sent and received trough the HTTP transport layer. The transport layer is able to maintain a number of HTTP connection objects. These connection objects are the ports.

A port group can work either in a client or a server mode.

*Client mode*

By means of a client port group, requests can be sent. The client port group handles the incoming responses.

Port groups have instant connection open, instant connection closed and use SSL properties. All of the ports in the group will have the same property setting.

Instant connection open means that before sending on a port, a connection open operation will be attempted on the port.

Instant connection close means that after receiving on a port, a connection close operation will be attempted on the port.

Use SSL is reserved for future use to implement security.

*Server mode*

By means of a server port group, a listen socket can be opened and responses can be sent to incoming requests. The server port group also handles incoming connections.

==== Persistent Connections

Server port groups support the persistent connection handling and the pipelining (see <<5-references.adoc#_2, [2]>>). A buffer is maintained for the responses so the responses will be sent in the order that the requests were received. The size of the buffer is a configuration parameter.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

None.

== External Templates

The application library defines three external template types.

* Template for request headers (*__CUSTOM_HEADER__*) with one mandatory parameter method and several optional parameters: `requestURI`, `versionMajor`, `versionMinor`, `customHeader`, `contentLength`.
* Template for response headers (*__CUSTOM_HEADER_RESPONSE__*) with the optional parameters: `status`, `versionMajor`, `versionMinor`, `contentLength`
* Template for bodies (`CUSTOM_BODY`) with no parameters. That is, template text is copied verbatim into the HTTP message.

Sample request header template:

[source]
----
$(method) latexmath:[$(requestURI)
HTTP/$](versionMajor).$(versionMinor)
DemoExternalHeader : test
Content-Length : $(contentLength)
$(customHeader)
----

Sample response header:

[source]
----
HTTP/latexmath:[$(versionMajor).$](versionMinor)
$(status)
DemoExternalHeader : test
Server: local
Content-Length : $(contentLength)
----

For proper encoding the template files shall use the standard Unix line separator: "\n".

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

In the application library three different encoding scenario has been implemented for header encoding, and two for body encoding.

=== Header – Internal Encoding

This is the base case when no external templates are defined and no `EPTF_HTTP_rawHeaderContentGetter_FT` function set. Message encoding is implemented in the HTTP test port (CNL 113 531). Message parameters are retrieved from the HTTP context.

=== Header – Raw Header

No encoding occurs when no external templates are defined and `EPTF_HTTP_rawHeaderContentGetter_FT` function is set. In this case the upper layer provides the encoded header to the Applib which in turn is copied verbatim to the outgoing HTTP message.

=== Header – External Template

External templates have the highest priority. If external templates are defined then external templates will be used whether any content getter function is set or not. The HTTP context provides the actual parameters to the external template instance.

==== Request Template

In this context the `customHeader` parameter will contain the header lines for the request template defined in the HTTP context.

==== Response Template

For adding further optional parameters to the response template type, the LGenBase feature provides the following function: `f_EPTF_LGenBase_extendTemplateType`. The number of additional template parameters must be set by means of the `f_EPTF_HTTP_addOptTempParamNumber` function in the AppLib.

The parameters values that should be assigned to the optional parameters added by the user must be set in the HTTP context by means of the `f_EPTF_HTTP_setOptTempParam` function.

=== Body – Internal Encoding and External Template

If external templates are defined the content of the external template will be used as the body of the HTTP message. Otherwise the body is determined by the getter function set in the HTTP context.

[[test_steps]]
== Test Steps

Test steps are used to apply the application library’s functionality in the finite state machine (FSM) of a specific traffic case. The user can extend basic test steps to achieve a more specific behavior.

[[f-eptf-http-step-sendrequest]]
=== `f_EPTF_HTTP_step_sendRequest`

This step sends an HTTP request based on HTTP context database and updates HTTP statistics. The query is assembled from the context database element which belongs to the entity to which the step has been applied.

[[f-eptf-http-step-handletimeout]]
=== `f_EPTF_HTTP_step_handleTimeout`

This step handles timeout after sending an HTTP request. The function currently does nothing. The user should set its own timeout handling step.

[[f-eptf-http-step-processresponse]]
=== `f_EPTF_HTTP_step_processResponse`

This step handles reception of HTTP response after sending an HTTP request. The function currently does nothing. The user should set its own message reception handling step.

[[f-eptf-http-step-closeportofuser]]
=== `f_EPTF_HTTP_step_closePortOfUser`

If a user sends on a port or on a port of a port group, then the port is associated to the user. This case the user can close its associated port by applying the current test step.

[[f-eptf-http-step-freeportofuser]]
=== `f_EPTF_HTTP_step_freePortOfUser`

If a user sends on a port or on a port of a port group, then the port is associated to the user. This case the user can make its associated port free for sending (without closing this) by applying the current test step.

[[f-eptf-http-step-sendconnect]]
=== `f_EPTF_HTTP_step_sendConnect`

This step sends an HTTP CONNECT request towards the HTTP connection object associated to the entity to which the step has been applied.

NOTE: If the connection id identifies a port group, then the request is applied to all ports in the port group.

[[f-eptf-http-step-sendclose]]
=== `f_EPTF_HTTP_step_sendClose`

This step sends an HTTP close request towards the HTTP connection object associated to the entity to which the step has been applied.

NOTE: If the connection id identifies a port group, then the request is applied to all ports in the port group.

[[f-eptf-http-step-sendhalfclose]]
=== `f_EPTF_HTTP_step_sendHalfClose`

This step sends an HTTP half close request towards the HTTP connection object associated to the entity to which the step has been applied.

Note that if the connection id identifies a port group, then the request is applied to all ports in the port group.

[[f-eptf-http-step-setentitycontexthttpmethodconnect]]
=== `f_EPTF_HTTP_step_setEntityContextHTTPMethodCONNECT`

This test step sets up the entity context to the CONNECT HTTP Method.

[[f-eptf-http-step-setentitycontexthttpmethoddelete]]
=== `f_EPTF_HTTP_step_setEntityContextHTTPMethodDELETE`

This test step sets up the entity context to the DELETE HTTP Method.

[[f-eptf-http-step-setentitycontexthttpmethodget]]
=== `f_EPTF_HTTP_step_setEntityContextHTTPMethodGET`

This test step sets up the entity context to the GET HTTP Method.

[[f-eptf-http-step-setentitycontexthttpmethodhead]]
=== `f_EPTF_HTTP_step_setEntityContextHTTPMethodHEAD`

This test step sets up the entity context to the HEAD HTTP Method.

[[f-eptf-http-step-setentitycontexthttpmethodoptions]]
=== `f_EPTF_HTTP_step_setEntityContextHTTPMethodOPTIONS`

This test step sets up the entity context to the OPTIONS HTTP Method.

[[f-eptf-http-step-setentitycontexthttpmethodpost]]
=== `f_EPTF_HTTP_step_setEntityContextHTTPMethodPOST`

This test step sets up the entity context to the POST HTTP Method.

[[f-eptf-http-step-setentitycontexthttpmethodput]]
=== `f_EPTF_HTTP_step_setEntityContextHTTPMethodPUT`

This test step sets up the entity context to the PUT HTTP Method.

[[f-eptf-http-step-setentitycontexthttpmethodtrace]]
=== `f_EPTF_HTTP_step_setEntityContextHTTPMethodTRACE`

This test step sets up the entity context to the TRACE HTTP Method.

[[f-eptf-http-step-handlerequest]]
=== `f_EPTF_HTTP_step_handleRequest`

This test step must be called to handle an incoming request.

[[f-eptf-http-step-sendresponse]]
=== `f_EPTF_HTTP_step_sendResponse`

This test step sends a response to a request.

[[f-eptf-http-step-closeport]]
=== `f_EPTF_HTTP_step_closePort`

This test step closes a port in the server port group.

[[f-eptf-http-step-cleanup]]
=== `f_EPTF_HTTP_step_cleanUp`

This test step cleans up the entity context.

== STEP Constants

The following step constants are defined in the application library:

[[c-eptf-http-stepidx-sendrequest]]
=== `c_EPTF_HTTP_stepIdx_sendRequest`

Scope: entity

Description: trigger for HTTP send request

[[c-eptf-http-stepidx-handletimeout]]
=== `c_EPTF_HTTP_stepIdx_handleTimeout`

Scope: entity

Description: trigger for HTTP timeout event

[[c-eptf-http-stepidx-responsereceived]]
=== `c_EPTF_HTTP_stepIdx_responseReceived`

Scope: entity

Description: trigger for HTTP response message reception event

[[c-eptf-http-stepidx-responsecharreceived]]
=== `c_EPTF_HTTP_stepIdx_responseCharReceived`

Scope: entity

Description: trigger for HTTP response message reception with charstring body event

[[c-eptf-http-stepidx-requestcharreceived]]
=== `c_EPTF_HTTP_stepIdx_requestCharReceived`

Scope: entity

Description: trigger for HTTP request message reception with charstring body event

[[c-eptf-http-stepidx-responseoctreceived]]
=== `c_EPTF_HTTP_stepIdx_responseOctReceived`

Scope: entity

Description: trigger for HTTP response message reception with binary body event

[[c-eptf-http-stepidx-requestcharreceived-0]]
=== `c_EPTF_HTTP_stepIdx_requestCharReceived`

Scope: entity

Description: trigger for HTTP request message reception with binary body event

[[c-eptf-http-stepidx-openconnection]]
=== `c_EPTF_HTTP_stepIdx_openConnection`

Scope: entity

Description: triggers an HTTP open connection event

[[c-eptf-http-stepidx-closeconnection]]
=== `c_EPTF_HTTP_stepIdx_closeConnection`

Scope: entity

Description: trigger for an HTTP close connection event

[[c-eptf-http-stepidx-halfcloseconnection]]
=== `c_EPTF_HTTP_stepIdx_halfCloseConnection`

Scope: entity

Description: trigger for an HTTP half close connection event

[[c-eptf-http-stepidx-closeportofuser]]
=== `c_EPTF_HTTP_stepIdx_closePortOfUser`

Scope: entity

Description: trigger for an HTTP close port of user event

[[c-eptf-http-stepidx-freeportofuser]]
=== `c_EPTF_HTTP_stepIdx_freePortOfUser`

Scope: entity

Description: trigger for an HTTP free port of user event

[[c-eptf-http-stepidx-setentitycontexthttpmethodconnect]]
=== `c_EPTF_HTTP_stepIdx_setEntityContextHTTPMethodCONNECT`

Scope: entity

Description: trigger for set up the HTTP CONNECT Method.

[[c-eptf-http-stepidx-setentitycontexthttpmethoddelete]]
=== `c_EPTF_HTTP_stepIdx_setEntityContextHTTPMethodDELETE`

Scope: entity

Description: trigger for set up the HTTP DELETE Method.

[[c-eptf-http-stepidx-setentitycontexthttpmethodget]]
=== `c_EPTF_HTTP_stepIdx_setEntityContextHTTPMethodGET`

Scope: entity

Description: trigger for set up the HTTP GET Method.

[[c-eptf-http-stepidx-setentitycontexthttpmethodhead]]
=== `c_EPTF_HTTP_stepIdx_setEntityContextHTTPMethodHEAD`

Scope: entity

Description: trigger for set up the HTTP HEAD Method.

[[c-eptf-http-stepidx-setentitycontexthttpmethodoptions]]
=== `c_EPTF_HTTP_stepIdx_setEntityContextHTTPMethodOPTIONS`

Scope: entity

Description: trigger for set up the HTTP OPTIONS Method.

[[c-eptf-http-stepidx-setentitycontexthttpmethodpost]]
=== `c_EPTF_HTTP_stepIdx_setEntityContextHTTPMethodPOST`

Scope: entity

Description: trigger for set up the HTTP POST Method.

[[c-eptf-http-stepidx-setentitycontexthttpmethodput]]
=== `c_EPTF_HTTP_stepIdx_setEntityContextHTTPMethodPUT`

Scope: entity

Description: trigger for set up the HTTP PUT Method.

[[c-eptf-http-stepidx-setentitycontexthttpmethodtrace]]
=== `c_EPTF_HTTP_stepIdx_setEntityContextHTTPMethodTRACE`

Scope: entity

Description: trigger for set up the HTTP TRACE Method.

[[c-eptf-http-stepidx-handlerequest]]
=== `c_EPTF_HTTP_stepIdx_handleRequest`

Index constant for `f_EPTF_HTTP_step_handleRequest`.

[[c-eptf-http-stepidx-sendresponse]]
=== `c_EPTF_HTTP_stepIdx_sendResponse`

Index constant for `f_EPTF_HTTP_step_sendResponse`.

[[c-eptf-http-stepidx-closeport]]
=== `c_EPTF_HTTP_stepIdx_closePort`

Index constant for `f_EPTF_HTTP_step_closePort`.

[[c-eptf-http-stepidx-cleanupcontext]]
=== `c_EPTF_HTTP_stepIdx_cleanUpContext`

Index constant for `f_EPTF_HTTP_step_cleanUpContext`.

== Inputs

[[c-eptf-http-inputidx-connectionopened]]
=== `c_EPTF_HTTP_inputIdx_connectionOpened`

Scope: entity

Description: trigger for an HTTP connection opened event

[[c-eptf-http-inputidx-connectionclosed]]
=== `c_EPTF_HTTP_inputIdx_connectionClosed`

Scope: entity

Description: trigger for an HTTP connection closed event

[[c-eptf-http-inputidx-errorreceived]]
=== `c_EPTF_HTTP_inputIdx_errorReceived`

Scope: entity

Description: trigger for an HTTP error reception event

[[c-eptf-http-inputidx-okreceived]]
=== `c_EPTF_HTTP_inputIdx_OKReceived`

Scope: entity

Description: trigger for an HTTP OK received event

[[c-eptf-http-inputidx-response100continue]]
=== `c_EPTF_HTTP_inputIdx_response100Continue`

Scope: entity

Description: trigger for an HTTP message reception event with status code 100

[[c-eptf-http-inputidx-response101switchingprotocols]]
=== `c_EPTF_HTTP_inputIdx_response101SwitchingProtocols`

Scope: entity

Description: trigger for an HTTP message reception event with status code 101

[[c-eptf-http-inputidx-response200ok]]
=== `c_EPTF_HTTP_inputIdx_response200OK`

Scope: entity

Description: trigger for an HTTP message reception event with status code 200

[[c-eptf-http-inputidx-response202accepted]]
=== `c_EPTF_HTTP_inputIdx_response202Accepted`

Scope: entity

Description: trigger for an HTTP message reception event with status code 202

[[c-eptf-http-inputidx-response203nonauthorativeinformation]]
=== `c_EPTF_HTTP_inputIdx_response203NonAuthorativeInformation`

Scope: entity

Description: trigger for an HTTP message reception event with status code 203

[[c-eptf-http-inputidx-response204nocontent]]
=== `c_EPTF_HTTP_inputIdx_response204NoContent`

Scope: entity

Description: trigger for an HTTP message reception event with status code 204

[[c-eptf-http-inputidx-response205resetcontent]]
=== `c_EPTF_HTTP_inputIdx_response205ResetContent`

Scope: entity

Description: trigger for an HTTP message reception event with status code 205

[[c-eptf-http-inputidx-response206partialcontent]]
=== `c_EPTF_HTTP_inputIdx_response206PartialContent`

Scope: entity

Description: trigger for an HTTP message reception event with status code 206

[[c-eptf-http-inputidx-response300multiplechoices]]
=== `c_EPTF_HTTP_inputIdx_response300MultipleChoices`

Scope: entity

Description: trigger for an HTTP message reception event with status code 300

[[c-eptf-http-inputidx-response301movedpermanently]]
=== `c_EPTF_HTTP_inputIdx_response301MovedPermanently`

Scope: entity

Description: trigger for an HTTP message reception event with status code 301

[[c-eptf-http-inputidx-response302found]]
=== `c_EPTF_HTTP_inputIdx_response302Found`

Scope: entity

Description: trigger for an HTTP message reception event with status code 302

[[c-eptf-http-inputidx-response303seeother]]
=== `c_EPTF_HTTP_inputIdx_response303SeeOther`

Scope: entity

Description: trigger for an HTTP message reception event with status code 303

[[c-eptf-http-inputidx-response304notmodified]]
=== `c_EPTF_HTTP_inputIdx_response304NotModified`

Scope: entity

Description: trigger for an HTTP message reception event with status code 304

[[c-eptf-http-inputidx-response305useproxy]]
=== `c_EPTF_HTTP_inputIdx_response305UseProxy`

Scope: entity

Description: trigger for an HTTP message reception event with status code 305

[[c-eptf-http-inputidx-response306unused]]
=== `c_EPTF_HTTP_inputIdx_response306Unused`

Scope: entity

Description: trigger for an HTTP message reception event with status code 306

[[c-eptf-http-inputidx-response307temporaryredirect]]
=== `c_EPTF_HTTP_inputIdx_response307TemporaryRedirect`

Scope: entity

Description: trigger for an HTTP message reception event with status code 307

[[c-eptf-http-inputidx-response400badrequest]]
=== `c_EPTF_HTTP_inputIdx_response400BadRequest`

Scope: entity

Description: trigger for an HTTP message reception event with status code 400

[[c-eptf-http-inputidx-response401unauthorized]]
=== `c_EPTF_HTTP_inputIdx_response401Unauthorized`

Scope: entity

Description: trigger for an HTTP message reception event with status code 401

[[c-eptf-http-inputidx-response402paymentrequired]]
=== `c_EPTF_HTTP_inputIdx_response402PaymentRequired`

Scope: entity

Description: trigger for an HTTP message reception event with status code 402

[[c-eptf-http-inputidx-response403forbidden]]
=== `c_EPTF_HTTP_inputIdx_response403Forbidden`

Scope: entity

Description: trigger for an HTTP message reception event with status code 403

[[c-eptf-http-inputidx-response404notfound]]
=== `c_EPTF_HTTP_inputIdx_response404NotFound`

Scope: entity

Description: trigger for an HTTP message reception event with status code 404

[[c-eptf-http-inputidx-response405methodnotallowed]]
=== `c_EPTF_HTTP_inputIdx_response405MethodNotAllowed`

Scope: entity

Description: trigger for an HTTP message reception event with status code 405

[[c-eptf-http-inputidx-response406notacceptable]]
=== `c_EPTF_HTTP_inputIdx_response406NotAcceptable`

Scope: entity

Description: trigger for an HTTP message reception event with status code 406

[[c-eptf-http-inputidx-response407proxyauthenticationrequired]]
=== `c_EPTF_HTTP_inputIdx_response407ProxyAuthenticationRequired`

Scope: entity

Description: trigger for an HTTP message reception event with status code 407

[[c-eptf-http-inputidx-response408requesttimeout]]
=== `c_EPTF_HTTP_inputIdx_response408RequestTimeout`

Scope: entity

Description: trigger for an HTTP message reception event with status code 408

[[c-eptf-http-inputidx-response409conflict]]
=== `c_EPTF_HTTP_inputIdx_response409Conflict`

Scope: entity

Description: trigger for an HTTP message reception event with status code 409

[[c-eptf-http-inputidx-response410gone]]
=== `c_EPTF_HTTP_inputIdx_response410Gone`

Scope: entity

Description: trigger for an HTTP message reception event with status code 410

[[c-eptf-http-inputidx-response411lengthrequired]]
=== `c_EPTF_HTTP_inputIdx_response411LengthRequired`

Scope: entity

Description: trigger for an HTTP message reception event with status code 411

[[c-eptf-http-inputidx-response412preconditionfailed]]
=== `c_EPTF_HTTP_inputIdx_response412PreconditionFailed`

Scope: entity

Description: trigger for an HTTP message reception event with status code 412

[[c-eptf-http-inputidx-response413requestentitytoolarge]]
=== `c_EPTF_HTTP_inputIdx_response413RequestEntityTooLarge`

Scope: entity

Description: trigger for an HTTP message reception event with status code 413

[[c-eptf-http-inputidx-response414requesturitoolong]]
=== `c_EPTF_HTTP_inputIdx_response414RequestURITooLong`

Scope: entity

Description: trigger for an HTTP message reception event with status code 414

[[c-eptf-http-inputidx-response415unsupportedmediatype]]
=== `c_EPTF_HTTP_inputIdx_response415UnsupportedMediaType`

Scope: entity

Description: trigger for an HTTP message reception event with status code 415

[[c-eptf-http-inputidx-response416requestedrangenotsatisfiable]]
=== `c_EPTF_HTTP_inputIdx_response416RequestedRangeNotSatisfiable`

Scope: entity

Description: trigger for an HTTP message reception event with status code 416

[[c-eptf-http-inputidx-response417expectationfailed]]
=== `c_EPTF_HTTP_inputIdx_response417ExpectationFailed`

Scope: entity

Description: trigger for an HTTP message reception event with status code 417

[[c-eptf-http-inputidx-response500internalservererror]]
=== `c_EPTF_HTTP_inputIdx_response500InternalServerError`

Scope: entity

Description: trigger for an HTTP message reception event with status code 500

[[c-eptf-http-inputidx-response501notimplemented]]
=== `c_EPTF_HTTP_inputIdx_response501NotImplemented`

Scope: entity

Description: trigger for an HTTP message reception event with status code 501

[[c-eptf-http-inputidx-response502badgateway]]
=== `c_EPTF_HTTP_inputIdx_response502BadGateway`

Scope: entity

Description: trigger for an HTTP message reception event with status code 502

[[c-eptf-http-inputidx-response503serviceunavailable]]
=== `c_EPTF_HTTP_inputIdx_response503ServiceUnavailable`

Scope: entity

Description: trigger for an HTTP message reception event with status code 503

[[c-eptf-http-inputidx-response504gatewaytimeout]]
=== `c_EPTF_HTTP_inputIdx_response504GatewayTimeout`

Scope: entity

Description: trigger for an HTTP message reception event with status code 504

[[c-eptf-http-inputidx-response505httpversionnotsupported]]
=== `c_EPTF_HTTP_inputIdx_response505HTTPVersionNotSupported`

Scope: entity

Description: trigger for an HTTP message reception event with status code 505

[[c-eptf-http-inputidx-response100class]]
=== `c_EPTF_HTTP_inputIdx_response100class`

Scope: entity

Description: trigger for an HTTP message reception event with status code in range [100 .. 200)

[[c-eptf-http-inputidx-response200class]]
=== `c_EPTF_HTTP_inputIdx_response200class`

Scope: entity

Description: trigger for an HTTP message reception event with status code in range [200 .. 300)

[[c-eptf-http-inputidx-response300class]]
=== `c_EPTF_HTTP_inputIdx_response300class`

Scope: entity

Description: trigger for an HTTP message reception event with status code in range [300 .. 400)

[[c-eptf-http-inputidx-response400class]]
=== `c_EPTF_HTTP_inputIdx_response400class`

Scope: entity

Description: trigger for an HTTP message reception event with status code in range [400 .. 500)

[[c-eptf-http-inputidx-response500class]]
=== `c_EPTF_HTTP_inputIdx_response500class`

Scope: entity

Description: trigger for an HTTP message reception event with status code in range [500 .. 600)

[[c-eptf-http-inputidx-responsesocketerror]]
=== `c_EPTF_HTTP_inputIdx_responseSocketError`

Scope: entity

Description: if transport layer cannot open or send message on a socket an IPL4 PortError arrives. This socket error notifies FSM, if any kind of socket error occurred.

== FSMs

No default FSMs provided by the application library.

== Statistics

The application library provides the following statistics:

[[c-eptf-http-stat-nofincrequests]]
=== `c_EPTF_HTTP_Stat_nofIncRequests`

Description: number of incoming requests.

[[c-eptf-http-stat-nofincoptionmessages]]
=== `c_EPTF_HTTP_Stat_nofIncOptionMessages`

Description: number of incoming messages with OPTIONS method

[[c-eptf-http-stat-nofoutoptionmessages]]
=== `c_EPTF_HTTP_Stat_nofOutOptionMessages`

Description: number of outgoing messages with OPTIONS method

[[c-eptf-http-stat-nofincgetmessages]]
=== `c_EPTF_HTTP_Stat_nofIncGetMessages`

Description: number of incoming messages with GET method

[[c-eptf-http-stat-nofoutrequests]]
=== `c_EPTF_HTTP_Stat_nofOutRequests`

Description: number of outgoing requests.

[[c-eptf-http-stat-nofoutgetmessages]]
=== `c_EPTF_HTTP_Stat_nofOutGetMessages`

Description: number of outgoing messages with GET method

[[c-eptf-http-stat-nofincheadmessages]]
=== `c_EPTF_HTTP_Stat_nofIncHeadMessages`

Description: number of incoming messages with HEAD method

[[c-eptf-http-stat-nofoutheadmessages]]
=== `c_EPTF_HTTP_Stat_nofOutHeadMessages`

Description: number of outgoing messages with HEAD method

[[c-eptf-http-stat-nofincportmessages]]
=== `c_EPTF_HTTP_Stat_nofIncPortMessages`

Description: number of incoming messages with POST method

[[c-eptf-http-stat-nofoutpostmessages]]
=== `c_EPTF_HTTP_Stat_nofOutPostMessages`

Description: number of outgoing messages with POST method

[[c-eptf-http-stat-nofincputmessages]]
=== `c_EPTF_HTTP_Stat_nofIncPutMessages`

Description: number of incoming messages with PUT method

[[c-eptf-http-stat-nofoutputmessages]]
=== `c_EPTF_HTTP_Stat_nofOutPutMessages`

Description: number of outgoing messages with PUT method

[[c-eptf-http-stat-nofincdeletemessages]]
=== `c_EPTF_HTTP_Stat_nofIncDeleteMessages`

Description: number of incoming messages with DELETE method

[[c-eptf-http-stat-nofoutdeletemessages]]
=== `c_EPTF_HTTP_Stat_nofOutDeleteMessages`

Description: number of outgoing messages with DELETE method

[[c-eptf-http-stat-nofinctracemessages]]
=== `c_EPTF_HTTP_Stat_nofIncTraceMessages`

Description: number of incoming messages with TRACE method

[[c-eptf-http-stat-nofouttracemessages]]
=== `c_EPTF_HTTP_Stat_nofOutTraceMessages`

Description: number of outgoing messages with TRACE method

[[c-eptf-http-stat-nofincconnectmessages]]
=== `c_EPTF_HTTP_Stat_nofIncConnectMessages`

Description: number of incoming messages with CONNECT method

[[c-eptf-http-stat-nofoutconnectmessages]]
=== `c_EPTF_HTTP_Stat_nofOutConnectMessages`

Description: number of outgoing messages with CONNECT method

[[c-eptf-http-stat-nofincresponses]]
=== `c_EPTF_HTTP_Stat_nofIncResponses`

Description: number of incoming responses.

[[c-eptf-http-stat-nofincxxxstatuscode]]
=== `c_EPTF_HTTP_Stat_nofIncXXXStatusCode`

Description: number of incoming messages with XXX status code where XXX denotes a valid status code (valid status codes are the ones defined in section <<test_steps, Test Steps>>)

[[c-eptf-http-stat-nofoutresponses]]
=== `c_EPTF_HTTP_Stat_nofOutResponses`

Description: number of outgoing responses.

[[c-eptf-http-stat-nofoutxxxstatuscode]]
=== `c_EPTF_HTTP_Stat_nofOutXXXStatusCode`

Description: number of outgoing messages with XXX status code where XXX denotes a valid status code (valid status codes are the ones defined in section <<test_steps, Test Steps>>)
