= Functional Specification

== Protocol Version Implemented

This protocol module contains the protocol messages and elements of the ICMP protocol (see <<5-references.adoc#_3, [3]>>, <<5-references.adoc#_4, [4]>>, <<5-references.adoc#_5, [5]>>, <<5-references.adoc#_6, [6]>>, <<5-references.adoc#_7, [7]>>, <<5-references.adoc#_8, [8]>>, <<5-references.adoc#_9, [9]>>), with the extensions for MIP available in <<5-references.adoc#_10, [10]>>, <<5-references.adoc#_11, [11]>>.

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Implemented Messages

All message types listed in protocol descriptions are implemented.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

None.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions that provide for the correct encoding of messages when sent from TITAN and correct decoding of messages when received by TITAN. The encoder updates the checksum field with the correct value. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|f_enc_PDU_ICMP
|PDU_ICMP
|octetstring

|f_dec_PDU_ICMP
|octetstring
|PDU_ICMP
|===
