= Terminology

* *Sockets:* +
The sockets is a method for communication between a client program and a server program in a network. A socket is defined as the "endpoint in a connection." Sockets are created and used with a set of programming requests or "function calls" sometimes called the sockets application programming interface (API). The most common sockets API is the Berkeley UNIX C language interface for sockets. Sockets can also be used for communication between processes within the same computer.

* *Single connection:* +
The test port controls a single connection, either initiated by the test sending a single `ASP_SunRPC_Connect` message, or the listening server accepts a single connection.

* *Multiple connections:* +
The test port controls multiple connections, either initiated by the test sending multiple `ASP_SunRPC_Connect` messages, or the listening server accepts multiple connections.

= Abbreviations

API:: Application Program Interface

ASP:: Abstract Service Primitive

IUT:: Implementation Under Test

RPC:: Remote Procedure Call

RTE:: Run-Time Environment

SUT:: System Under Test

SSL:: Secure Sockets Layer

TTCN-3:: Testing and Test Control Notation version 3
