= Introduction

== About This Document

=== How to Read This Document

This is the User Guide for the NS v7.3.0 protocol module. The NS v7.3.0 protocol module is developed for the TTCN-3 Toolset with TITAN. This document should be read together with Function Specification ‎<<3-references.adoc#_3, [3]>>.

=== Presumed Knowledge

To use this protocol module the knowledge of the TTCN-3 language ‎‎<<3-references.adoc#_1, [1]>> and TITAN Test Executor ‎‎<<3-references.adoc#_2, [2]>> is essential.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor R7A (1.7.pl0) or higher installed. For installation guide see ‎‎<<3-references.adoc#_5, [5]>>.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R7A.

Protocol modules implement the message structures of the related protocol in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language ‎‎<<3-references.adoc#_1, [1]>> and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment ‎‎<<3-references.adoc#_2, [2]>>.

Protocol modules are using Titan’s RAW encoding attributes ‎‎<<3-references.adoc#_4, [4]>> and hence are usable with the Titan test toolset only.

== Installation

The set of protocol modules can be used in developing TTCN-3 test suites using any text editor. However to make the work more efficient a TTCN-3-enabled text editor is recommended (e.g. `nedit`, `xemacs`). Since the NS protocol is used as a part of a TTCN-3 test suite, this requires TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of ‎‎<<3-references.adoc#_5, [5]>>.

== Configuration

None.
