= Terminology

*TitanSim Core Library (CLL):* +
It is that part of the TitanSim software that is totally project independent. (i.e., which is not protocol-, or application-dependent). The EPTF Core Library is to be supplied and supported by the TCC organization. Any EPTF Core Library development is to be funded centrally by Ericsson.

*TitanSim Variables:* +
They contain values, from which _TitanSim Statistics_ can be calculated automatically on changes or periodically.

*TitanSim Statistics Measure:* +
It is a feature responsible for creating _TitanSim Statistics_ and updating their value when required.

*TitanSim Statistics:* +
They are Statistics of TTCN-3 Variables. Possible Statistics are among others minimum, maximum, mean, standard deviation, etc. and also the content of a Variable can be a Statistics itself. The values of such Statistics are automatically updated in the background.

*Capture Group:* +
It is a concept for grouping Statistics references with the same _Sampling Time_ together, capturing referenced Statistics at sampling intervals and printing contents of the group to the log files assigned to the group.

*Sampling Time:* +
It is defined per _Capture Group_, in seconds. It is the time period, at which the Statistics contained by a capture group are sampled and printed out to the log files.

*Capture Control Mode:* +
It is a functionality which allows choosing between several capture control modes for starting and stopping statistics capture, such as: _Manual_ _Load-based_ and _Complete_ _Capture Control_ modes.

*Manual Capture Control:* +
It is a _Capture Control Mode_ that starts/stops the statistics capture according to a manual user interaction (for example a button pressed on the TitanSim GUI).

*Load-based Capture Control:* +
It is a _Capture Control Mode_, which makes it possible to start/stop capture according to load stability measured in the system. The load Variable can be any user-defined load-related parameter supported by the TitanSim tool (for example the cps generated by the tool, CPU load of the IUT, etc.).

*Complete Capture Control:* +
It is a _Capture Control Mode_, which starts statistics capture automatically when the test execution is started and automatically stops it when the test execution is finished.

= Abbreviations

CLL:: Core Library

EPTF:: Ericsson Load Test Framework, formerly TITAN Load Test Framework

TitanSim:: Ericsson Load Test Framework, formerly TITAN Load Test Framework

TTCN-3:: Testing and Test Control Notation version 3 <<9-references.adoc#_1, ‎[1]>>.
