= Installation and Configuration

Since the EPTF CLL is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of these functions. For more details on the installation of TTCN-3 Test Executor see the relevant section of ‎<<5-references.adoc#_2, ‎[2]>>.

If not otherwise noted in the respective sections, the following are needed to use the EPTF CLL features:

* Copy the files of the specific feature from the released _EPTF_Core_Library_CNL113512/src_ directory of the test suite or create symbolic links to them.
* Import the released demo application from _EPTF_Core_Library_CNL113512/demo_ or write your own application using the given CLL feature.
* Import required files from _EPTF_Core_Library_CNL113512/src_ from other EPTF CLL features as explained in the User Guide of the feature (see _EPTF_Core_Library_CNL113512/doc)._
* Create _Makefile_ or modify the existing one. For more details see the relevant section of the User Guide of the feature from _EPTF_Core_Library_CNL113512/doc._
* Edit the configuration file according to your needs, see the User Guide of the specific _EPTF_Core_Library_CNL113512/doc_ for configuration and module parameters.

Some of the features of the Core Library are using constants defined during compilation. These constants can be defined with the EPTF_DEBUG switch which can be set in the CPPFLAGS section of the _Makefile_. If this macro is defined the application will run in debug mode otherwise not.
