= Terminology

*TitanSim Application Library:* +
It is that part of the TitanSim software that is (at-least partially) project dependent. (I.e., which is protocol-, and/or application-dependent). Any TitanSim application library is to be supplied and supported _either_ by the customer project _only_; or by the customer project _together_ with the TCC organization. Any TitanSim application library development is to be funded by the ordering projects.

*TitanSim Core (Load) Library(CLL):* +
It is that part of the TitanSim software that is totally project independent. (I.e., which is not protocol-, or application-dependent). The TitanSim CLL is to be supplied and supported by the TCC organization. Any TitanSim CLL development is to be funded centrally by Ericsson.

*Application Library (AppLib):* +
It is that part of the TitanSim software that is although protocol, or application-area dependent, but can be _reused_ across many TitanSim applications. `AppLibs` are dependent on the CLL.

*Control Logic:* +
It is that part of the TitanSim software that is specific to a particular TitanSim application program. It is usually not directly reusable and is built upon the CLL and several `AppLibs`.

*Entities:* +
They are "things/objects" that are simulated by the LGen. Such "things" are usually the "users", "calls", "servers", "terminations", or anything whose external behavior is to be simulated by the `LGen`. Usually an `LGen` simulates more than one entity.

*Entity context:* +
It is an index-able generic data record describing an entity. It serves as a hub connecting all information related to the entity together by referring the respective associated _behavior contexts_ and _FSM contexts_ via their indices. The entity contexts are identified via their indices with respect to the entity context database stored in the `v_LGenBase_entities` component variable.

*Behavior context:* +
It is an index-able (set of) data record(s) that stores data and state information of a given entity with respect to a given _behavior type._ Storage for behavior contexts is to be provided by the respective AppLibs.

*Behavior type:* +
It is a concept for collectively referring a set of _behavior contexts, FSM inputs, test steps,_ and functions realizing methods conforming to given function signatures prescribed by the `LGenBase` feature. Behavior types are to be declared dynamically during run-time to the `LGenBase` by the component-type initialization function of some `AppLib`. Usually an `AppLib` product has only one behavior type, but it is permitted for `AppLibs` to declare more than one behavior types, if necessary. Behavior types are identified by their indices determined by the order of declaration and the declarations are stored in `v_LGenBase_behaviorTypes`

*Entity type:* +
It is a named list of references to declared _behavior types_. As such, it declares what type of behavior contexts are available on entities of this type.

*Entity group:* +
A group of entities with homogenous entity type. The indices of the entities of the group make a continuous interval that does not overlap with the indices range of any other entity group.

*Test step:* +
Test steps are functions whose signature conforms to a given function type. They _must_ not contain TTCN-3 statement with blocking semantics.

*FSM table:* +
It is a formal specification of the communication rules of Finite State Machines. These indexable records are stored in `v_LGenBase_fsmTables`. FSM tables realizing _traffic cases_ must obey certain rules.

*Traffic case type:* +
It is a prototype used as an input for instantiating traffic case instances on a specific entity group. It defines what _FSM table_ to use, what _entity type_ must be used by the _entity group_ where the _traffic case_ is to be deployed

*Traffic case:* +
It is a behavior, defined by an FSM table, that is executed on a given entity group. All entities of the entity group participate in executing the the traffic case. An entity group may have more than one concurrent traffic cases.

*Scenario:* +
It is a collection of traffic cases deployed on an entity group.

*TitanSim Variables:* +
They are enhanced component variables that make it possible to access the values of other Variables in remote components.

*TitanSim Statistics:* +
They are Statistics of TitanSim Variables. Possible Statistics are among others minimum, maximum, mean, standard deviation, etc. and also the content of a Variable can be a Statistics itself. The values of such Statistics are automatically and periodically updated in the background.

*Generated load of a traffic case:* +
It is defined as the _aggregate_ load generated by _traffic case instances_ of the given _traffic case_

*Generated load of the traffic mix:* +
It is defined as the _aggregate_ load generated by the individual _traffic cases_ of the given _traffic mix_

*Programming style, event driven:* +
A programming style not-so ``natural'' for most people. It is atypical for function tests. It focuses on one or more threads of execution, however, _not_ in a sequential manner. Rather it defines states for execution where the program code wait for an event (any event) to happen, then based on the event it executes a state transition to a new state and continues to wait for another event. The flow of events _cannot be_ understood easily just by reading the source code sequentially, therefore it is less natural for many programmer.

*Programming style, procedural:* +
It is typical for functions tests. It focuses on a single thread of execution in a sequential manner. The "natural" programming style for most programmers, since the flow of events can be understood easily just by reading the source code sequentially.

*Traffic case instance:* +
It is a specific execution instance of the behavior (message sequence) defined by the _traffic case_

*Traffic generator PTC:* +
It is a PTC that actually generate the messages toward the SUT during the performance test campaign

*Traffic group:* +
It is a named instance of a _traffic mix_. Such traffic group may have _ TitanSim Parameters_ that are common to each traffic cases within the group that realize the _traffic mix_. Such traffic group may have (potentially aggregate) _ TitanSim Statistics_ that provides (potentially aggregate) information about the execution of the _ traffic cases_ within the group. Note, however, that the _ traffic cases_ may have individual parameters and statistics, as well.

*Traffic mix:* +
It is a specific combination of _traffic cases_ that are to be executed concurrently by TitanSim. Each traffic case has a corresponding _traffic weight assigned._ The traffic mix has a load-level target that is an aggregate of the individual load-levels of the individual _traffic cases_, whose load levels are the result of the execution of their _traffic case instances_

= Abbreviations

API:: Application Programming Interface

EPTF:: Ericsson Load Test Framework, formerly TITAN Load Test Framework

FOA:: First Office Application

IUT:: Implementation Under Test

LGen:: Load Generator PTC

PTC:: Parallel Test Component

SUT:: System Under Test

TLTF:: See EPTF
