= Functionality

The protocol module implements the message structure of the Message Session Relay Protocol (MSRP), using the standard specification language TTCNv3. This allows defining of test data (templates) in the TTCNv3 language ‎<<8-references.adoc#_2, [2]>> and correctly encoding/decoding these messages when executing test suites using the TITAN TTCNv3 test environment.

Protocol module is using TITAN’S TEXT encoding attributes <<8-references.adoc#_3, [3]>> and hence is usable with the TITAN test toolset only.

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of https://tools.ietf.org/html/rfc4975[RFC4975].

== Routing Functionality

Routing functionality is not performed.

== Modified and Non-Implemented Protocol Elements

=== Relaxed Conditions

There is no constraint between received and sent messages.

The terminology of v19 is applied for both protocol versions.

[[ericsson_specific_changes]]
== Ericsson-Specific Changes

There is no Ericsson specific change in this product.

== Backward Incompatibilities

None.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor version R7A (1.7.pl0) or higher installed. For installation guide see <<8-references.adoc#_2, [2]>>.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R7A.
