= Protocol Modules

== Overview

Protocol modules implement the message structure of the related protocol in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language <<8-references.adoc#_1, [1]>> and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

Protocol module uses TITAN’S TEXT encoding attributes <<8-references.adoc#_2, [2]>> and hence is usable with the TITAN test toolset only.

== Installation

The set of protocol modules can be used for developing TTCN-3 test suites using any text editor. However, to make the work more efficient a TTCN-3- enabled text editor is recommended (e.g. `nedit`, `xemacs`). Since the MSRP protocol is used as a part of a TTCN-3 test suite, this requires Titan TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<8-references.adoc#_2, [2]>>.

== Configuration

== Module Parameters

There is a boolean module parameter for debugging purposes of encode/decode functions:

`tsp_MSRP_EncDec_debug`*

Its default value is `_false_`, thus in order to have debug information about encoding and decoding it must be set to `_true_` in the test suite configuration file in the `[MODULE_PARAMETERS]` section.

`tsp_MSRP_EncDec_IPv6_bracketing`

It controls the automatic bracketing of IPv6 addresses. Its default value is `_true_`, thus in order to disable the automatic bracketing it must be set to `_false_` in the test suite configuration file in the `[MODULE_PARAMETERS]` section.

== Parser Generation Rules

In order to generate the _.c_ and _.h_ files from _.y_ and _.l_ the following _Makefile_ rules must be used:

[source]
----
MSRP_parse_.tab.c MSRP _parse_.tab.h: MSRP.y
bison -dv -p MSRP _parse_ -b MSRP _parse_ $<
lex. MSRP _parse_.c: MSRP.l
flex -Cfr -8 -Bvpp -P MSRP _parse_ MSRP.l
----
The _.h_ and _.c_ parser files should be generated during the protocol module development. Only the pregenerated files are needed for test case development and test execution.
