= Functionality

The Socket API contains type and constant definitions in a formalized way, using the standard specification language TTCN-3. This allows the usage of these definitions in test ports, protocol modules, libraries and applications.

== Implemented Protocols

None.

=== Modified and Non-Implemented Protocol Elements

None.

=== Ericsson-Specific Changes

None.

== Backward Incompatibilities

None.

== System Requirements

Socket API is a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* Titan TTCN-3 Test Executor version CRL 113 200 R7A (1.7.pl0) or higher installed. For Installation Guide see <<5-references.adoc#_2, [2]>>.

NOTE: This version of the test port is not compatible with Titan releases earlier than CRL 113 200 R7A.
