= Functionality

== Product Contents, Structure

The major parts of RPMG are:

a. _ATTR.awk_ script: This is the most important part of the product.

b. A pair of encoder and decoder functions to invoke RAW encoder/decoder.

c. __RADIUS_Mapping.ttcn__ module: provide the authentication.

The RADIUS Base Protocol <<11-references.adoc#_1, [1]>> and other RADIUS applications are specified in RDFs developed by TCC as part of the RPMG product.

The TTCN-3 module (`RADIUS_Types`) that is generated by the script varies between applications, thus it is NOT a product.

== Protocol Version Implemented

Currently the following applications are supported:

[width="100%",cols="85%,15%",options="header",]
|=====================================================
|RDFs |Refs.
|__BaseTypes_IETF_RFC2865.rdf__ |<<11-references.adoc#_1,[1]>>
|__Accounting_IETF_RFC2866_RFC2867.rdf__ |<<11-references.adoc#_5, [5]>>, <<11-references.adoc#_12, [12]>>
|__TunnelAuthentication_IETF_RFC2868.rdf__ |<<11-references.adoc#_6, [6]>>
|__Extensions_IETF_RFC2869.rdf__ |<<11-references.adoc#_7, [7]>>
|__IPv6_IETF_RFC3162.rdf__ |<<11-references.adoc#_8, [8]>>
|__DynamicAuthorizationExtensions_IETF_RFC5176.rdf__ |<<11-references.adoc#_9, [9]>>
|__ChargeableUserIdentity_IETF_RFC4372.rdf__ |<<11-references.adoc#_10, [10]>>
|__GGSN_FS_46_15517_CSA113_4RevB.rdf__ |<<11-references.adoc#_11, [11]>>
|=====================================================

[width="100%",cols="85%,15%",options="header",]
|===============================
|Vendor specific RDFs |Refs.
|_Cisco.rdf_ |
|_Juniper.rdf_ |
|_Scap.rdf_ |
|_Smartedge.rdf_ |<<11-references.adoc#_13, [13]>>
|_Vendor.rdf_ |
|_skt.rdf_ |
|__Vendor_detailed_ericsson.rdf__ |
|===============================

[width="100%",cols="85%,15%",options="header",]
|=======================================
|RDFs (in obsolate) |Refs.
|_RadiusBaseTypes.rdf_ |<<11-references.adoc#_1, [1]>>
|_RadiusAccountingAttributes.rdf_ |<<11-references.adoc#_5, [5]>>
|_TunnelAuthenticationAttributes.rdf_ |<<11-references.adoc#_6, [6]>>
|_RadiusExtensions.rdf_ |<<11-references.adoc#_7, [7]>>
|_RadiusAndIPv6.rdf_ |<<11-references.adoc#_8, [8]>>
|_RadiusAuthExtensions.rdf_ |<<11-references.adoc#_9, [9]>>
|_RadiusGGSN.rdf_ |<<11-references.adoc#_11, [11]>>
|=======================================

== Routing Functionality

Routing functionality is not performed.

== Modified and Non-Implemented Protocol Elements

None.

== Ericsson-Specific Changes

None.

== Backward Incompatibilities

None.

== System Requirements

The RADIUS protocol module generator consist of several RDF files, contains different application definitions of RADIUS protocols and an AWK script which read the RDF files and generates the __RADIUS_Types.ttcn__ type definition module.

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor R7A (1.7.pl0) or higher installed. For installation guide see <<11-references.adoc#_14, [14]>>.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R7A.

* The RADIUS protocol module generator contains functions, use MD5 checksum, so the same OpenSSL must be installed as used in TITAN. For installation guide see <<11-references.adoc#_16, [16]>>.
