= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the WTP protocol. The modules are based on WAP-224-WTP-20010710-a (see <<5-references.adoc#_1, [1]>>). The following messages are implemented:

* `Concatenation`
* `Invoke`
* `Result`
* `Ack`
* `Abort`
* `Segmented_Invoke`
* `Segmented_Result`
* `NegativeAck`

=== Unimplemented Messages, Information Elements and Constants

None.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

None.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions, which assure correct RAW encoding of messages when sent from TITAN and correct RAW decoding of messages when received by TITAN. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name |Type of formal parameters |Type of return value
|`enc_PDU_WTP` |PDU_WTP |octetstring
|`dec_PDU_WTP` |octetstring |PDU_WTP
|===
