= Functionality

The MobileL3 v13.4.0 protocol module implements the message structures of the related protocol <<5-references.adoc#_5, [5]>> in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

The MobileL3 v13.4.0 protocol module uses Titan’s RAW encoding attributes <<5-references.adoc#_1, [1]>> and hence is usable with the Titan test toolset only.

== Implemented Protocols

This set of protocol modules implements a subset of protocol messages and constants of the Mobile L3 protocol. It includes GMM, SM, RRM, SMS and SS. SM and GMM are based on 24.008 v13.4.0 (see <<5-references.adoc#_4, [4]>>), RRM are based on 44.018 v13.0.0 (see <<5-references.adoc#_5, [5]>>), SMS are based on 24.011 v13.0.0 (see <<5-references.adoc#_6, [6]>>) and 23.040 v13.0.0 (see <<5-references.adoc#_7, [7]>>) and SS are based on 24.080 v13.0.0 (see <<5-references.adoc#_8, [8]>>) with the modifications specified in <<modifications-deviations-related-to-the-protocol-specification, Modifications/Deviations Related to the Protocol Specification>>.

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Unimplemented and Implemented Messages, Information Elements and Constants

==== Messages for Mobility Management (MM)

All the messages are implemented according to Table 9.2.1 and 10.2 of 24.008 (see <<5-references.adoc#_4, [4]>>).

==== Messages for Circuit Switched Call Control (CC)

All the messages are implemented according to Table 9.54 and 9.3 of 24.008 (see <<5-references.adoc#_4, [4]>>).

==== GPRS Mobility Management (GMM) Messages

All the messages are implemented according to Table 10.4 of 24.008 (see <<5-references.adoc#_4, [4]>>).

==== GPRS Session Management (SM) Messages

All the messages are implemented according to Table 10.4a of 24.008 (see <<5-references.adoc#_4, [4]>>).

==== Common Information Elements (CommonIE)

All the information elements implemented according to 10.5.1 of 24.008 (see <<5-references.adoc#_4, [4]>>).

==== Radio Resource Management (RRM) Messages

Some of the messages that are used are implemented according to table 9.1.1 of 44.018 (see <<5-references.adoc#_5, [5]>>).

==== Short Message Service (SMS) Messages

All the CP-messages are implemented according to 7.2 of 24.011 (see <<5-references.adoc#_6, [6]>>).

All the RP-messages are implemented according to 7.3 of 24.011 (see <<5-references.adoc#_6, [6]>>).

All the TPDU-messages are implemented according to 9.2.2 of 23.040 (see <<5-references.adoc#_7, [7]>>).

==== Supplementary Service Management (SS) Messages

All the SS-messages are implemented according to table 2.1 of 24.080 (see <<5-references.adoc#_8, [8]>>).

=== Ericsson-Specific Changes

None.

== Backward Incompatibilities

None.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* Titan TTCN-3 Test Executor version CRL 113 200/5 R4A (5.4.pl0) or higher installed. For Installation Guide see <<5-references.adoc#_2, [2]>>.

NOTE: This version of the test port is not compatible with Titan releases earlier than CRL 113 200/5 R4A.
