= Workflow

== Installation

Since `EPTF_CLL_DataSource` is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of these functions. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<7-references.adoc#_2, [2]>>.

If not otherwise noted in the respective sections, the following are needed to use `EPTF_CLL_DataSource`:

* Copy the files listed in Section <<2-datasource.adoc#usage_dependencies, Usage Dependencies>> to the directory of the test suite or create symbolic links to them.
* Import the DataSource demo or write your own application using DataSource
* Create _Makefile_ or modify the existing one. For more details see the relevant section of <<7-references.adoc#_2, [2]>>.
* Edit the configuration file according to your needs, see following section <<configuration, Configuration>>.

[[configuration]]
== Configuration

The executable test program behavior is determined via the run-time configuration file. This is a simple text file, which contains various sections. The usual suffix of configuration files is _.cfg_. For further information on the configuration file see <<7-references.adoc#_2, [2]>>.

This DataSource feature defines TTCN-3 module parameters as defined in <<7-references.adoc#_2, [2]>>, clause 4. Actual values of these parameters – when no default value or a different from the default actual value wished to be used – shall be given in the `[MODULE_PARAMETERS]` section of the configuration file.

This DataSource feature defines the following module parameters:

* `tsp_EPTF_DataSource_maxWaitTime := 10.0`
* `tsp_EPTF_DataSource_subscriptionMode := realtime`
* `tsp_EPTF_DataSource_refreshRate := -1`

Default values for the default refresh rate and subscription mode arguments of the `f_EPTF_DataSource_getData` function.

== Runtime Test Configuration Design (Deployment)

Any component in the runtime configuration can extend the `EPTF_DataSource_CT` or the `EPTF_DataSourceClient_CT` components. Even a single component can extend both component types at the same time.
