= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the MIME protocol (see <<5-references.adoc#_3, [3]>>, <<5-references.adoc#_4, [4]>>) with the modifications specified in <<modifications-deviations-related-to-the-protocol-specification, Modifications/Deviations Related to the Protocol Specification>>.

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Implemented Messages, Content Types, Content Encodings and Constants

The following Content encodings are implemented from <<5-references.adoc#_3, [3]>>, <<5-references.adoc#_4, [4]>>: Base64, binary, 7bit and 8bit. The quoted-printable encoding is not implemented.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

The quoted-printable encoding is not implemented.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions, which assure correct encoding of messages when sent from Titan and correct decoding of messages when received by Titan. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`f_MIME_Encode`
|in PDU_MIME_entity
|returns charstring

|`f_MIME_Decode`
|in charstring
|return PDU_MIME_entity;
