= Introduction

== About This Document

=== How to Read This Document

This is the User Guide for the Statistics Capture Control of the Ericsson Performance Test Framework (TitanSim), Core Library (CLL). EPTF Core Library is developed for the TTCN-3 <<7-references.adoc#_1, [1]>> Toolset with TITAN <<7-references.adoc#_2, [2]>>. This document should be read together with the Function Description of the Statistics Capture Control feature <<7-references.adoc#_5, [5]>> . For more information on the EPTF Core Library, see the User Guide <<7-references.adoc#_4, [4]>> and the Function Specification <<7-references.adoc#_3, [3]>> of the TitanSim. Additionally, to understand the functionality of this feature, read the documentation of the Variable <<7-references.adoc#_7, [7]>> and the Statistics Measure <<7-references.adoc#_8, [8]>> features.

== System Requirements

In order to use the Statistics Capture Control feature the system requirements listed in EPTF Core Library User Guide <<7-references.adoc#_4, [4]>> should be fulfilled.

Additionally, this feature also uses the functionalities of the TCC Useful Function product <<7-references.adoc#_7, [7]>>.

== Release Information

This document contains actualized information on the TitanSim Release R7A01. The new functionalities compared to the release R2A02 concerning the EPTF Statistics Capture Control feature are the following:

* The feature is extended with the client component. The existing component behaves like before and adds server functionalities.
* The changes are backward-compatible to the initial release R2A01 and tested according to this requirement.
