= Functional Specification

== Protocol Version Implemented

This protocol module contains the protocol messages and elements of the TCP protocol (see <<5-references.adoc#_3, [3]>>),

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Implemented Messages

All message types listed in protocol description are implemented.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

None.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions that provide for the correct encoding of messages when sent from TITAN and correct decoding of messages when received by TITAN. The encoder can be instructed to update the checksum field with the correct value. The encoder can also be instructed  to update the data offset field with the correct value. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name |Type of formal parameters |Type of return value
|`f_enc_PDU_TCP` |IP_Address, //src. IPv4 or IPv6 address +
IP_Address, //dest. IPv4 or IPv6 address +
PDU_TCP, +
boolean // automatically calculate data offset +
boolean // automatically calculate checksum | octetstring
|`f_dec_PDU_TCP` |octetstring |PDU_TCP
|===

There is also a function which verifies the `checksum` field in an encoded TCP message:

[cols=3*,options=header]
|===
|Name |Type of formal parameters |Type of return value
|`f_TCP_verify_checksum` |octetstring, IP_Address, IP_Address |boolean
|===
