= Introduction

== About This Document

=== How to Read This Document

This is the User’s Guide for the _HTTPmsg_CNL113312_ (called HTTP from now on) test port. The HTTP test port is developed for the TTCN-3 Toolset with TITAN according to the Functional Specification <<10_references.adoc#_3, [3]>>.
=== Prerequisite Knowledge

The knowledge of the TITAN TTCN-3 Test Executor <<10_references.adoc#_2, [2]>> and the TTCN-3 language <<10_references.adoc#_1, [1]>> is essential. Basic knowledge of the HTTP protocol is valuable when reading this document.


== System Requirements

In order to operate the HTTP test port the following system requirements must be satisfied:

* Platform: any platform supported by TITAN RTE, optional OpenSSL.
* TITAN TTCN-3 Test Executor R8A (1.8.pl0) or higher installed. For installation guide see <<10_references.adoc#_2, [2]>>

NOTE: This version of the test port is not compatible with TITAN releases earlier than R8A.

* The C compiler gcc version 2.95 or above is installed.
* The OpenSSL 0.9.7 or above is installed. See <<10_references.adoc#_5, [5]>>.
* The Abstract_Socket CNL 113 384, rev. R6A or later product has to be installed.

== Fundamental Concepts

The test port establishes connection between the TTCN-3 test executor and the HTTP server or client trough a TCP/IP socket connection. The test port transmits and receives HTTP1.1 messages; see <<10_references.adoc#_3, [3]>> and <<10_references.adoc#_4, [4]>>
