= The Test Port

== Overview

The HTTP test port offers HTTP message primitives and TCP connection control ASPs to the test suite in TTCN-3 format. The TTCN-3 definition of the HTTP messages and TCP notification ASPs can be found in a separate TTCN-3 module. This module should be imported into the test suite.

== Installation

Since the HTTP test port is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of the HTTP test port. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<10_references.adoc#_2, [2]>>

When building the executable test suite intended to handle HTTP over SSL connections, the libraries compiled for the OpenSSL toolkit and the TTCN-3 Test Executor should also be linked into the executable.

Using and compiling OpenSSL is optional in the test port. See <<10_references.adoc#_5, [5]>> for more information. OpenSSL libraries should be added to the _Makefile_ generated by the TITAN executor see example in close <<8_examples.adoc#makefile, Makefile>>.

== Configuration

The executable test program behavior is customized via the RTE configuration file. This is a simple text file, which contains various sections (e.g. `[TESTPORT_PARAMETERS]`) after each other. The usual suffix of the RTE configuration file is _.cfg_. For further information about the configuration file see <<10_references.adoc#_2, [2]>>

[[HTTP_test_port_parameters_in_the_RTE_configuration_file]]
=== HTTP Test Port Parameters in the RTE Configuration File

In the `[TESTPORT_PARAMETERS]` section you can specify parameters that are passed to the test ports. Each parameter definition consists of a component name, a port name, a parameter name and a parameter value. The component name can be either an identifier or a component reference (integer) value. The port and parameter names are identifiers while the parameter value must always be a charstring (with quotation marks). Instead of component name or port name (or both of them) the asterisk ("*") sign can be used, which means "all components" or "all ports of the component". More information about the RTE configuration file can be found in <<10_references.adoc#_2, [2]>>

In the `[TESTPORT_PARAMETERS]` section the following parameters can be set for the HTTP test port. Parameters marked with bold fonts apply to *SSL* using HTTP test ports *only*. Parameter values are *case-sensitive*!

`use_notification_ASPs`

Enables receiving of `Connect_result`, `Client_connected` and `Listen_result` ASPs. Its default value is `_"no"_` in order to provide backward-compatibility for test suites using the port versions older than R2A.

`server_backlog`

The parameter can be used to specify the number of allowed pending (queued) connection requests on the port the server listens. It is optional in server mode and not used in client mode. The default value is `_"1024"_`.

`http_debugging`

Enables detailed debugging in the test port. It has only effect when TTCN_DEBUG is also set within the logging parameters of the configuration file. Its default value is `_"no"_`.

`TRUSTEDCALIST_FILE`

It specifies a PEM encoded file’s path on the file system containing the certificates of the trusted CA authorities to use. Mandatory in server mode, and mandatory in client mode if VERIFYCERTIFICATE=`_"yes"_`.

`VERIFYCERTIFICATE`

The parameter is *optional*, and can be used to tell the HTTP test port whether to check the certificate of the other side. If it is defined `_"yes"_`, the test port will query and check the certificate. If the certificate is not valid (i.e. the public and private keys do not match), it will exit with a corresponding error message. If it is defined `_"no"_`, the test port will not check the validity of the certificate. The default value is `_"no"_`.

`KEYFILE`

This parameter is *conditional*. It specifies a PEM encoded file’s path on the file system containing the RSA private key. Mandatory in server mode and optional in client mode.

`CERTIFICATEFILE`

This parameter is *conditional*. It specifies a PEM encoded file’s path on the file system containing the certificate chain. For detailed information see <<10_references.adoc#_5, [5]>> Mandatory in server mode and optional in client mode. Note that the server may require client authentication. In this case no connection can be established without a client certificate.

`PASSWORD`

The parameter is *optional*, and can be used to specify the password protecting the private key file. The PASSWORD has to be the password used by generation of the private key file. If the password is not defined, the SSL toolkit asks for it when the test port receives the `LISTEN` ASP. It is recommended to define it in the config file instead.

== Start Procedure

=== TTCN-3 Test Executor

Before the executable test suite can be run the TTCN-3 modules and C++ codes should be compiled and linked into an executable program. This process can be automated using the make utility. For more information about the _Makefile_ see the *_Makefile_* section and <<10_references.adoc#_2, [2]>>

NOTE: The c++ implementation files __HTTPmsg_PT.hh__, __HTTPmsg_PT.cc__, __Abstract_Socket.cc__, __Abstract_Socket.hh__ and the TTCN-3 modules __HTTPmsg_Types.ttcn__ and __HTTPmsg_PortType.ttcn__ of the test port should be included in the _Makefile_.

For information on how to start the execution see <<10_references.adoc#_2, [2]>>

=== Connecting to a Server

In case of the test performs the role of a HTTP client, the `Connect` ASP has to be sent. Its parameters are:

`hostname`: host name or IP address of the remote server.

`portnumber`: port number of the remote server where it accepts connections.

`use_ssl`: has to be `_false_` on normal TCP/IP connections, `_true_` if the server accepts HTTPS connections.

Multiple parallel connections can be opened and used. If two or more connections are used in parallel, `use_notification_ASPs` parameter has to be set to `_true_`, see <<HTTP_test_port_parameters_in_the_RTE_configuration_file, HTTP Test Port Parameters in the RTE Configuration File>>. In this case `Connect_result` ASP is returned to the test case with the `client_id` associated to the connection. The returned `client_id` has to be used in the messages targeted to send on this connection. The returned `client_id` with value `_–1_` means that the server did not accept the connection because an error occurred.

=== Starting a Server, Listening for Client Connections

In case of the test performs the role of a HTTP server, the `Listen` ASP has to be sent. Its parameters are:

`local_hostname`: host name or IP address of the interface in the local computer. It should be set if the workstation has multiple IP interfaces, and the test has to use a specific one.

`portnumber`: port number where the server will accept connections.

`use_ssl`: has to be `_false_` to accept normal TCP/IP connections, `_true_` to accept HTTPS connections.

Sending the `Listen` ASP multiple times will cause to close the listening port and open another one.

If `use_notification_ASPs` parameter is set to `_true_` in the configuration, the `Listen_result` ASP is returned to the test case with the opened port number. The returned `portnumber` with value `_–1_` means that an error occurred while setting up the requested listening port.

If a client connects to the server and `use_notification_ASPs` parameter is set to `_true_` in the configuration, the `Client_connected` ASP is sent to the test case with `_hostname_`, `_portnumber_` and `_client_id_` fields. `client_id` has to be used as described above.

[[sending-receiving-http-messages]]
== Sending/receiving HTTP Messages

The HTTP test port is able to send and receive `HTTPMessage` structures. The `HTTPMessage` can be one of the following types:

* `HTTPRequest` +
The Request message represents a single request to perform by the HTTP server, usually to access a `resource` on the server.
* `HTTPResponse` +
The Response message is sent by the HTTP server to the client. It includes the return status code of the request and the requested resource.
* `HTTPRequest_binary_body` +
The same as the `HTTPRequest` message. It is passed to TTCN when the body of the message contains non-ascii characters.
* `HTTPResponse_binary_body` +
The same as the `HTTPResponse` message. It is passed to TTCN when the body of the message contains non-ascii characters.

In case of multiple connections, the `client_id` will identify the connection. When sending an HTTP message, it has to be set to the corresponding connection id. When receiving the message, the test port sets it to the corresponding connection id, and the test case will get the right value.

Apart from the `HTTPRequest` and `HTTPResponse` ASPs above, the `erronous_msg` is received by the test port and sent to the test suite:

`HTTP_erronous_msg` +
If a message is received on the connection, which can not be decoded as a `HTTP1.1` or `HTTP1.0` message, the `HTTPMessage` will contain an erroneous message with a `client_id`, and sent to the test suite.

== Stop Procedure

=== Closing Connections

To close a specific client connection, the `Close` ASP has to be sent with the relevant `client_id`. If `client_id` is `_omit_`, all client connections will be closed.

To close the server listening port, the `Shutdown` ASP has to be sent.

If `use_notification_ASPs` parameter is set to `_true_` in the configuration, the test case will receive the `Close` ASP if the remote end of the connection disconnects. The `client_id` field will identify the relevant connection.

If the remote end closes the connection, a `Half_close` ASP is received by the test case. `Half_close` means that the remote end will not send any more data, but it may receive. Some test cases may use this functionality, but in most cases a `Close` ASP has to be sent in reply to it, with the `client_id` received in the `Half_close` message.

[[ttcn-3-test-executor-0]]
=== TTCN-3 Test Executor

The TITAN executor stops the test port after the test case is finished or in case of execution error during the test case.
