= Regexp functions

== Overview

The system functions implement non-TTCN-3 regular expression support functions

Regexp Functions are implemented in the following files:

* __TCCRegexp_Functions.ttcn__
* _TCCRegexp.cc_

== Function Definitions

`external function f_pcre_regexp(in charstring instr, in charstring expression, in integer groupno) return charstring;`

This function returns the substring of the input character string instr, which is the content of n-th group matching to the expression. The expression is a Perl compatible regular expression pattern. The number of the group to be returned is specified by `groupno`, which shall be a positive integer or `_zero_`. Group numbers are assigned by the order of occurrences of the opening bracket of a group and counted starting from 1 by step 1. If the `groupno` is `_zero_`, a substring matched by the entire pattern is returned. If no substring fulfilling all conditions (i.e. pattern and group number) is found within the input string, an empty string is returned.

`external function f_pcre_regexp_list(in charstring instr,in charstring expression) return charstring_list;`

This function returns a list of substrings of the input character string instr, which are the content of n-th group matching to the expression. The expression is a Perl compatible regular expression pattern. Group numbers are assigned by the order of occurrences of the opening bracket of a group and counted starting from 1 by step 1.

`external function f_pcre_regexp_list_all_matches(in charstring instr,in charstring expression) return t_list_of_charstring_list;`

This function returns the full list of the substring of the input character string instr, which is the content of n-th group matching to the expression. The expression is a Perl compatible regular expression pattern. Group numbers are assigned by the order of occurrences of the opening bracket of a group and counted starting from 1 by step 1. If no substring fulfilling all conditions is found within the input string, an empty record of is returned.

The functions are based on the PCRE library. See: http://www.pcre.org/

== Error Messages

`*Compilation of the pcre regexp failed at position x. Reason: yyyyy*`

The supplied expression is not a valid PCRE expression.

== Warning Messages

None.

== Examples

`f_pcre_regexp( "abc", "(a|(z))(bc)" ,0)`

returns "abc"

`f_pcre_regexp( "abc", "(a|(z))(bc)" ,1)`

returns "a"

`f_pcre_regexp( "abc", "(a|(z))(bc)" ,2)`

returns ``´´. The second sub expression is the "(z)"

`f_pcre_regexp( "abc", "(a|(z))(bc)" ,3)`

returns "bc"

`f_pcre_regexp_list( "abc", "(a|(z))(bc)")`

returns \{ "abc" , "a" , ”” , "bc"}

`f_pcre_regexp_list_all_matches("a1 b1 a2", "(a)(\d)")`

returns \{ \{ "a1", "a", "1" }, \{ "a2", "a", "2" } }
