= Functional Specification

== Protocol Version Implemented

This protocol module contains the protocol messages and elements of the ICMPv6 protocol (see <<5-references.adoc#_3, [3]>> and <<5-references.adoc#_4, [4]>>),

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Implemented Messages

All message types listed in protocol descriptions are implemented.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

None.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions that provide for the correct encoding of messages when sent from TITAN and correct decoding of messages when received by TITAN. The encoder updates the checksum field with the correct value. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`f_enc_PDU_ICMPv6`
|PDU_ICMPv6, OCT16, OCT16
|octetstring

|`f_dec_PDU_ICMPv6`
|octetstring
|PDU_ICMPv6
|===

There is also a function which verifies the `checksum` field in an encoded ICMPv6 message:

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`f_ICMPv6_verify_checksum` 
|octetstring, OCT16, OCT16
|boolean
|===
