= Functional Specification

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the SUA protocol (see <<5-references.adoc#_1, [1]>>).

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

=== Implemented Messages

All SUA message types of message classes 0, 2, 3, 4, 7, 8 and 9 as listed in chapter 3.1.2 of <<5-references.adoc#_1, [1]>> will be implemented.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

None.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions that assure correct encoding of messages when sent from Titan and correct decoding of messages when received by Titan. Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`f_enc_PDU_SUA`
|PDU_SUA
|octetstring

|`f_dec_PDU_SUA`
|octetstring
|PDU_SUA
|===
