= Warning Messages

The following warning messages can occur while using the DNS protocol module. The warning messages are self-explanatory:

`*While encoding PDU_DNS: `header.qdCount' (_n_) differs from size of `queries' (_m_).*`

`*While encoding PDU_DNS: `header.anCount' (_n_) differs from size of `answers' (_m_).*`

`*While encoding PDU_DNS: `header.nsCount' (_n_) differs from size of `nameServerRecords' (_m_).*`

`*While encoding PDU_DNS: `header.arCount' (_n_) differs from size of `additionalRecords' (_m_).*`

`*Forward reference in compressed domain name at octet #_n_.*`

`*While decoding resource record: not enough octets, decoding to field `undecodable'. Resource record starts at octet #_n_.*`

`*Resource record class _n_ is not supported. rData will be decoded to field 'unsupported'.*`

`*While decoding address resource record: not enough octets, decoding to field 'undecodable'.*`

`*While decoding SOA resource record: not enough octets, decoding to field 'undecodable'.*`

`*While decoding WKS resource record: not enough octets, decoding to field 'undecodable'.*`

`*While decoding WKS resource record: rdLength is less than 6. Decoding to field 'undecodable'.*`

`*While decoding HINFO resource record: not enough octets, decoding to field 'undecodable'.*`

`*While decoding MX resource record: not enough octets, decoding to field 'undecodable'.*`

`*While decoding AAAA resource record: not enough octets, decoding to field 'undecodable'.*`

`*While decoding SRV resource record: not enough octets, decoding to field 'undecodable'.*`

`*While decoding NAPTR resource record: not enough octets, decoding to field 'undecodable'.*`

`*Resource record type _n_ is not supported. RData will be decoded to field 'unsupported'.*`

`*While decoding resource record: rdLength (_n_) does not equal the length of decoded resource record data (_m_). Resource record starts at octet #_k_.*`

`*Length of rData (_n_) in octets differs from rdLength (_m_) in resource record: "…"*`

`*While encoding domain name: domain name is empty.*`

`*In case of Resource record class n rdLength and ttl fields must be zero. rData will be decoded to field 'unsupported'.*`
