= References

Methods for Testing and Specification (MTS); The Testing and Test Control Notation version 3. Part 1: Core Language European Telecommunications Standards InstituteES 201 873-1 Version 4.5.1, April 2013

Methods for Testing and Specification (MTS); The Testing and Test Control Notation version 3. Part 4: TTCN–3 Operational SemanticsEuropean Telecommunications Standards Institute. ES 201 873-4 Version 4.4.1, April 2012

Methods for Testing and Specification (MTS); The Testing and Test Control Notation version 3. Part 7: Using ASN.1 with TTCN–3 European Telecommunications Standards Institute.ES 201 873-7 Version 4.5.1, April 2013

Methods for Testing and Specification (MTS); The Testing and Test Control Notation version 3. Part 9: Using XML Schema with TTCN–3 European Telecommunications Standards Institute.ES 201 873-9 Version 4.5.1, April 2013

ITU-T, X.690, Information TechnologyASN.1 encoding rules: Specification of Basic Encoding Rules (BER), Canonical Encoding Rules (CER) and Distinguished Encoding Rules (DER)International Telecommunication Union, November 2008

ITU-T, X.693, Information TechnologyASN.1 encoding rules: XML Encoding Rules (XER), November 2008

ITU-T, X.693 amendment 1, Information TechnologyASN.1 encoding rules: XER encoding instructions and EXTENDED-XER, November 2008

ISO/IEC 10646-1, Information technology – Universal Multiple-Octet Coded Character Set (UCS) – Part 1: Architecture and Basic Multilingual Plane, Second edition, 200009-15

RFC3629: UTF-8, a transformation format of ISO 10646

User Guide for TITAN TTCN-3 Test Executor1/198 17-CRL 113 200/6 Uen

Installation Guide for TITAN TTCN-3 Test Executor1/1531-CRL 113 200/6 Uen

Release Notes109 47-CRL 113 200/6 Uen

Technical Reference for TITAN TTCN-3 Test Executor2/198 17-CRL 113 200/6 Uen

David A. Wheeler, Program Library HOWTO: http://tldp.org/HOWTO/Program-Library-HOWTO/index.html

ETSI ES 202 781 V1.4.1. (2015-06 Methods for Testing and Specification (MTS); The Testing and Test Control Notation version 3; TTCN-3 Language Extensions: Configuration and Deployment Support)
