= Introduction

== About This Document

=== How to Read This Document

This is the User Guide for the Real Time Streaming Protocol (RTSP) protocol module. The Real Time Streaming Protocol (RTSP) protocol module is developed for the TTCN-3 Toolset with TITAN. This document should be read together with  Function Specification <<5-references.adoc#_3, [3]>>.

=== Presumed Knowledge

To use this protocol module the knowledge of the TTCN-3 language <<5-references.adoc#_1, ‎[1]>> is essential. Basic knowledge of the RTSP <<5-references.adoc#_5, [5]>> protocol is valuable when reading this document.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor version R8B (1.8.pl1) or higher installed. For installation guide see <<5-references.adoc#_2, [2]>>.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R8B.
