= Functionality

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the IP protocol, version 4 (see <<5-references.adoc#_1, ‎[1]>>) and version 6 (see <<5-references.adoc#_2, ‎[2]>>) with the modifications specified in <<modifications-deviations-related-to-the-protocol-specification, Modifications/Deviations Related to the Protocol Specification>>.

The following IPv4 extension headers are supported:

* authentication header (*_AH_*), see ‎<<5-references.adoc#_6, [6]>>
*
* encapsulating security payload (*_ESP_*), see ‎<<5-references.adoc#_7, [7]>>

* generic routing encapsulation (*_GRE_* and *_GRE2_*), see <<5-references.adoc#_8, ‎[8]>> and <<5-references.adoc#_9, ‎[9]>>

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

The IPv4 options at the end of the header are not supported.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions, which assure correct encoding of messages when sent from TITAN and correct decoding of messages when received by TITAN.

Function `f_IPv4_enc_eth` puts padding zeros to the end of the encoded IP message if shorter than 46 bytes, it assures the minimal length of payload in case of Ethernet frame is used as lower layer.

Implemented encoding/decoding functions:

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`f_IPv4_enc`
|(IPv4_packet)
|returns octetstring

|`f_IPv4_enc_eth`
|(IPv4_packet)
|returns octetstring

|`f_IPv4_dec`
|(octetstring)
|returns IPv4_packet

|`f_IPv4_dec_backtrack`
|(octetstring, IPv4_packet,boolean)
|returns integer

|`f_IPv6_enc`
|(IPv6_packet)
|returns octetstring

|`f_IPv6_dec`
|(octetstring)
|returns IPv6_packet

|`f_IPv6_dec_backtrack`
|(octetstring, IPv6_packet,boolean)
|returns integer
|===

NOTE: In general, the length values are automatically calculated regardless of user input. One exception is the `exthdr_length` field where the value is automatically calculated only if the tester uses the dummy value `_-1_`. If the tester uses values from `_0_` to `_255_` for `exthdr_length` then the user-defined value will be encoded.

The 3^rd^ parameter of the backtrack decoders control the payload length check. If the parameter is `_true_`, the length of the payload part and the payload length in the IP header are compared and the decoding will fail if they are not equal. If the parameter is `_false_` the length check if not enforced, which is useful for handling truncated IP datagrams.

The default value of the parameter is controlled by the `tsp_use_strict_length_check` module parameter, which default value is `_true_`.

The product also provides some additional functionality to the user via the following functions:

* The `f_IPv4_checksum`() can be used to calculate the IPv4 checksum over an already encoded IPv4 packet.

* The `f_IPv4_addr_enc`() and `f_IPv4_addr_dec`() functions can be used to convert IPv4 addresses from character string format to encoded octetstring format and vice versa.

* The `f_IPv6_addr_enc` and `f_IPv6_addr_dec`can be used for IPv6 addresses. The functions with backtrack postfix are giving back `_0_` integer if the decoding failed and `_1_` if it was successful. The decoded value will be in the second parameter.

The functions return an empty string if the conversion of the address is not possible.

[cols=3*,options=header]
|===

|Name
|Type of formal parameters
|Type of return value

|`f_IPv4_checksum`
|(octetstring)
|returns OCT2

|`f_IPv4_addr_enc`
|(IPV4ADDR)
|returns octetstring

|`f_IPv4_addr_dec`
|(octetstring)
|returns IPV4ADDR

|`f_IPv6_addr_enc`
|(charstring)
|returns octetstring

|`f_IPv6_addr_dec`
|(octetstring)
|returns charstring
|===
