= Functionality

Protocol modules implement the message structures of the related protocol in a formalized way, using the standard specification language ASN.1 <<5-references.adoc#_7, [7]>>. This allows defining of test data (templates) in the TTCN-3 language <<5-references.adoc#_1, [1]>> and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

== Protocol Version Implemented

This set of protocol modules implements protocol messages and constants of the SNMP protocol, (see <<5-references.adoc#_2, [2]>>, <<5-references.adoc#_3, [3]>>, <<5-references.adoc#_4, [4]>>, <<5-references.adoc#_5, [5]>>). SNMPv1, SNMPv2 and SNMPv3 messages are supported.

[[modifications-deviations-related-to-the-protocol-specification]]
== Modifications/Deviations Related to the Protocol Specification

None.

=== Unimplemented Messages, Information Elements and Constants

None.

[[protocol-modifications-deviations]]
=== Protocol Modifications/Deviations

None.

== System Requirements

Protocol modules are a set of ASN.1 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor version R7A (1.7.pl0) or higher installed.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R7A.
