= Central Scheduling

== Overview

The EPTF Central Scheduling feature makes it possible to write load test cases using similar methodology than in function test. Load testing means executing several traffic cases in parallel.

Scheduling of the traffic case triggering is performed by the Central Scheduling Application Admin. The triggering is done by sending execution burst messages to load generators which will execute the selected traffic case(s). The load generator and the interface between the admin and the load generator must be implemented by the user.

[[description_of_files_in_this_feature]]
== Description of Files in This Feature

The EPTF CLL Central Scheduling API includes the following files:

* Central Scheduling
** __EPTF_CLL_CS_Definitions.ttcnpp__ - This TTCN-3 module contains common type definitions that should be used in all Central Scheduling Components.
** __EPTF_CLL_CS_Admin_Functions.ttcnpp__ - This TTCN-3 module contains the implementation of the Central Scheduling Application Admin Base functions.
** __EPTF_CLL_CS_LB_Functions.ttcnpp__ - This TTCN-3 module contains the implementation of the Load Balancing for Central Scheduling.
** __EPTF_CLL_CS_UIHandler_Definitions.ttcnpp__ - This module contains common type definitions that should be used if a GUI is needed for Central Scheduling.
** __EPTF_CLL_CS_UIHandler_Functions.ttcnpp__ - This module contains the implementation of the Central Scheduling with GUI support.

[[description_of_required_files_from_other_features]]
== Description of Required Files from Other Features

The Central Scheduling feature is part of the TitanSim EPTF Core Load Library (CLL). It relies on several features of the CLL. To use the Central Scheduling, the user has to obtain the respective files from the following features:

* `Common`
* `Base`
* `ExecCtrl`
* `LGenBase`
* `FreeBusyQueue`
* `UIHandler`
* `Variable`

== Installation

Since `EPTF_CLL_CentralScheduling` is used as a part of the TTCN-3 test environment this requires TTCN-3 Test Executor to be installed before any operation of these functions. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<7-references.adoc#_2, [2]>>.

If not otherwise noted in the respective sections, the following are needed to use `EPTF_CLL_CentralScheduling`:

* Copy the files listed in sections <<description_of_files_in_this_feature, Description of Files in This Feature>> and <<description_of_required_files_from_other_features,  Description of Required Files from Other Features>> to the directory of the test suite or create symbolic links to them.
* Import the Central Scheduling demo or write your own application using Central Scheduling.
* Create _Makefile_ or modify the existing one. For more details see the relevant section of <<7-references.adoc#_2, [2]>>.
* Edit the config file according to your needs, see following section <<configuration, Configuration>>.

[[configuration]]
== Configuration

The executable test program behavior is determined via the run-time configuration file. This is a simple text file, which contains various sections. The usual suffix of configuration files is _.cfg_. For further information on the configuration file see <<7-references.adoc#_2, [2]>>.

This Central Scheduling feature defines TTCN-3 module parameters as defined in <<7-references.adoc#_2, [2]>>, clause 4. Actual values of these parameters – when no default value or a different from the default actual value wished to be used – shall be given in the `[MODULE_PARAMETERS]` section of the configuration file.

=== Module Parameters of the Central Scheduling Feature

`tsp_EPTF_CS_LGenHostnameList`

This `EPTF_CharstringList` type module parameter is defined in module `EPTF_CLL_CS_Definitions`. It is used to define the Hostnames on which load generators are to be created.

Its default value is `_{}_`.

`tsp_debug_EPTF_CLL_CS_LB_Functions`

This boolean type module parameter is defined in module `EPTF_CLL_CS_LB_Functions`. It can be used for debugging purposes.

Its default value is `_false_`.

`tsp_debug_EPTF_CS_Admin_Functions`

This boolean type module parameter is defined in module `EPTF_CLL_CS_Admin_Functions`. It can be used for debugging purposes.

Its default value is `_false_`.

`tsp_EPTF_CLL_CS_Admin_LgenStatusGuard`

This float type module parameter is defined in module `EPTF_CLL_CS_Admin_Functions`. It defines the maximum time a load generator can take to initialize and send its initial status message. After this time expires with no status received, the Admin stops with an error message.

The default value of this parameter is `_10.0 _` for 10 seconds.

`tsp_EPTF_CLL_CS_Admin_LGenCreationDelay`

This float type module parameter is defined in module `EPTF_CLL_CS_Admin_Functions`. It defines a delay between successive creation of load generators. Its default value is `_0.1_`.

=== Configuring Traffic Cases

Entity group for traffic cases can be created via the LGenBase module parameter `tsp_LGenBase_EntityGrpDeclarators` with the entity name `CS_Entity_Tc`<suffix> where <suffix> is defined by `v_EPTF_CS_EntityName_Suffix` in the user init function.

Traffic cases and scenarios can be configured via the following LGenBase module parameters:

* `tsp_LGenBase_TcMgmt_tcTypeDeclarators2`
* `tsp_LgenBase_TcMgmt_WeightedScenarioDeclarators`
* `tsp_LGenBase_Scenarios2Grps`

For details, see <<7-references.adoc#_7, [7]>>. For an example, see the demo in the demo directory.

=== Configuring Load Generators

The Central Scheduler Application Admin declares entities of type `CS_Entity_LGen<suffix>` where `<suffix>` is defined by calling the function `f_EPTF_CS_Admin_setEntityNameSuffix` in the user init function. These entities can be used to define the number of load generators used by a specific type of Central Scheduling. This can be done by creating an entity group of this entity type via the LGenBase module parameter `tsp_LGenBase_EntityGrpDeclarators`.

No scenario must be stared on the load generator entities. Load generator entities are handled automatically without a scenario and their entities and entity group are only needed to be able to split load generators between multiple Admins using the ExecCtrl feature.

=== DataSource function of Central Scheduling

See the natural documentation of the CentralScheduling feature.
